GLC_lib: GLC_RepFlyMover Class Reference
GLC_RepFlyMover Class Reference
GLC_RepFlyMover : Fly representation.
#include <glc_repflymover.h>
Public Member Functions
Constructor / Destructor
GLC_RepFlyMover (GLC_Viewport *pViewport)
Default constructor.
GLC_RepFlyMover (const GLC_RepFlyMover &repFlyMover)
Copy constructor.
virtual ~GLC_RepFlyMover ()
Destructor.
Get Functions
virtual GLC_RepMover * clone () const
Return a clone of the flymover.
Set Functions
virtual void update ()
Update the representation.
virtual void setMainColor (const QColor &color)
Set representation main color.
virtual void setThickness (double thickness)
Set representation wire thickness.
OpenGL Functions
virtual void glDraw ()
Virtual interface for OpenGL Geometry set up.
Public Member Functions inherited from GLC_RepMover
GLC_RepMover (GLC_Viewport *)
Default constructor.
GLC_RepMover (const GLC_RepMover &)
Copy constructor.
virtual ~GLC_RepMover ()
Destructor.
QColor mainColor ()
Return the main Color.
virtual void init ()
Init the representation.
void setRepMoverInfo (RepMoverInfo *pRepMoverInfo)
Set the repMoverInfo of this rep.
void render ()
Representation OpenGL Execution.
Private Member Functions
void createRepresentation ()
Create the plane representation.
Private Attributes
double m_Radius
Center Circle radius.
GLC_3DViewInstance m_CenterCircle
Center Circle.
GLC_3DViewInstance m_Plane
Plane.
GLC_3DViewInstance m_Hud
HUD.
GLC_Vector2d m_HudOffset
HUD offset.
Additional Inherited Members
Protected Member Functions inherited from GLC_RepMover
Protected Attributes inherited from GLC_RepMover
GLC_Viewport * m_pViewport
The viewport.
QColor m_MainColor
The rep main color.
double m_Thickness
The rep wire thickness.
GLC_RenderProperties m_RenderProperties
The rep rendering properties.
RepMoverInfo * m_pRepMoverInfo
The repmover info of this rep.
Detailed Description
GLC_RepFlyMover : Fly representation.
Definition at line 37 of file glc_repflymover.h.
Constructor & Destructor Documentation
GLC_RepFlyMover::GLC_RepFlyMover (GLC_Viewport * pViewport)
Default constructor.
Definition at line 32 of file glc_repflymover.cpp.
References createRepresentation().
Referenced by clone().
GLC_RepFlyMover::GLC_RepFlyMover (const GLC_RepFlyMover & repFlyMover)
Copy constructor.
Definition at line 44 of file glc_repflymover.cpp.
GLC_RepFlyMover::~GLC_RepFlyMover () virtual
Destructor.
Definition at line 55 of file glc_repflymover.cpp.
Member Function Documentation
GLC_RepMover * GLC_RepFlyMover::clone () const virtual
Return a clone of the flymover.
Implements GLC_RepMover.
Definition at line 60 of file glc_repflymover.cpp.
References GLC_RepFlyMover().
void GLC_RepFlyMover::createRepresentation () private
Create the plane representation.
Definition at line 153 of file glc_repflymover.cpp.
References GLC_3DViewInstance::addGeometry(), GLC_Polylines::addPolyline(), m_CenterCircle, m_Hud, m_HudOffset, GLC_RepMover::m_MainColor, m_Plane, m_Radius, GLC_RepMover::m_Thickness, GLC_Geometry::setLineWidth(), GLC_Geometry::setWireColor(), GLC_Vector2d::x(), and GLC_Vector2d::y().
Referenced by GLC_RepFlyMover().
void GLC_RepFlyMover::glDraw () virtual
Virtual interface for OpenGL Geometry set up.
Implements GLC_RepMover.
Definition at line 101 of file glc_repflymover.cpp.
References GLC_Context::current(), GLC_Context::glcEnableLighting(), GLC_Context::glcLoadIdentity(), GLC_Context::glcMatrixMode(), GLC_Context::glcOrtho(), GLC_Context::glcPopMatrix(), GLC_Context::glcPushMatrix(), m_CenterCircle, GLC_RepMover::RepMoverInfo::m_DoubleInfo, m_Hud, m_Plane, GLC_RepMover::m_pRepMoverInfo, GLC_RepMover::m_pViewport, GLC_3DViewInstance::render(), glc::TransparentRenderFlag, GLC_Viewport::viewHSize(), GLC_Viewport::viewVSize(), and glc::WireRenderFlag.
void GLC_RepFlyMover::setMainColor (const QColor & color) virtual
Set representation main color.
Reimplemented from GLC_RepMover.
Definition at line 85 of file glc_repflymover.cpp.
References GLC_3DViewInstance::geomAt(), m_CenterCircle, m_Hud, m_Plane, GLC_RepMover::setMainColor(), and GLC_Geometry::setWireColor().
void GLC_RepFlyMover::setThickness (double thickness) virtual
Set representation wire thickness.
Reimplemented from GLC_RepMover.
Definition at line 93 of file glc_repflymover.cpp.
References GLC_3DViewInstance::geomAt(), m_CenterCircle, m_Hud, m_Plane, GLC_Geometry::setLineWidth(), and GLC_RepMover::setThickness().
void GLC_RepFlyMover::update () virtual
Update the representation.
Reimplemented from GLC_RepMover.
Definition at line 65 of file glc_repflymover.cpp.
References GLC_RepMover::RepMoverInfo::m_DoubleInfo, m_Plane, GLC_RepMover::m_pRepMoverInfo, m_Radius, GLC_RepMover::RepMoverInfo::m_VectorInfo, GLC_3DViewInstance::setMatrix(), GLC_Vector3d::x(), and glc::Z_AXIS().
Member Data Documentation
GLC_3DViewInstance GLC_RepFlyMover::m_CenterCircle private
Center Circle.
Definition at line 105 of file glc_repflymover.h.
Referenced by createRepresentation(), glDraw(), setMainColor(), and setThickness().
GLC_3DViewInstance GLC_RepFlyMover::m_Hud private
HUD.
Definition at line 111 of file glc_repflymover.h.
Referenced by createRepresentation(), glDraw(), setMainColor(), and setThickness().
GLC_Vector2d GLC_RepFlyMover::m_HudOffset private
HUD offset.
Definition at line 114 of file glc_repflymover.h.
Referenced by createRepresentation().
GLC_3DViewInstance GLC_RepFlyMover::m_Plane private
Plane.
Definition at line 108 of file glc_repflymover.h.
Referenced by createRepresentation(), glDraw(), setMainColor(), setThickness(), and update().
double GLC_RepFlyMover::m_Radius private
Center Circle radius.
Definition at line 102 of file glc_repflymover.h.
Referenced by createRepresentation(), and update().
The documentation for this class was generated from the following files:
glc_repflymover.h
glc_repflymover.cpp
©2005-2013 Laurent Ribon