GLC_lib: GLC_Renderer Class Reference
GLC_Renderer Class Reference
GLC_Renderer : Is used to store and retrieve overload rendering properties.
#include <glc_renderer.h>
Public Member Functions
Constructor / Destructor
GLC_Renderer ()
GLC_Renderer (GLC_3DViewCollection *pCollection)
GLC_Renderer (const GLC_Renderer &other)
virtual ~GLC_Renderer ()
Get Functions
bool hasCollection () const
Return true if this renderer has an attached collection.
GLC_3DViewCollection * collection () const
Return the 3DView collection attached to this renderer.
bool instanceRenderPropertiesIsAvailable (GLC_uint id) const
Return true if the renderProperties of the given instance id is available.
const GLC_RenderProperties & renderPropertiesOfInstance (GLC_uint id) const
Return the renderProperties of the given instance id.
bool isCurrent () const
Return true if this renderer is current.
Set Functions
void clear ()
Clear the content of this render.
GLC_Renderer & operator= (const GLC_Renderer &other)
Assignement operator.
void setCollection (GLC_3DViewCollection *pCollection)
Set the collection to use.
void setCurrent ()
Set this renderer the current renderer.
void unSetCurrent ()
Unset this rendere the current rendere.
void addRenderPropertiesOfInstanceId (GLC_uint id)
Add the renderProperties of the given instance id.
Private Attributes
GLC_3DViewCollection * m_pCollection
The 3DView collection attached to this renderer.
QHash< GLC_uint,
GLC_RenderProperties > m_IdToRenderProperties
bool m_IsCurrent
Detailed Description
GLC_Renderer : Is used to store and retrieve overload rendering properties.
An GLC_Renderer is attached to a GLC_3DViewCollection
The renderer is used to render a scene in a specific way.
Definition at line 43 of file glc_renderer.h.
Constructor & Destructor Documentation
GLC_Renderer::GLC_Renderer ()
Definition at line 31 of file glc_renderer.cpp.
GLC_Renderer::GLC_Renderer (GLC_3DViewCollection * pCollection)
Definition at line 39 of file glc_renderer.cpp.
GLC_Renderer::GLC_Renderer (const GLC_Renderer & other)
Definition at line 47 of file glc_renderer.cpp.
GLC_Renderer::~GLC_Renderer () virtual
Definition at line 55 of file glc_renderer.cpp.
References clear().
Member Function Documentation
void GLC_Renderer::addRenderPropertiesOfInstanceId (GLC_uint id)
Add the renderProperties of the given instance id.
Definition at line 134 of file glc_renderer.cpp.
References GLC_3DViewCollection::contains(), GLC_3DViewCollection::instanceHandle(), m_IdToRenderProperties, m_pCollection, and GLC_3DViewInstance::renderPropertiesHandle().
void GLC_Renderer::clear (void)
Clear the content of this render.
Definition at line 71 of file glc_renderer.cpp.
References m_IdToRenderProperties, and m_pCollection.
Referenced by setCollection(), and ~GLC_Renderer().
GLC_3DViewCollection* GLC_Renderer::collection () const inline
Return the 3DView collection attached to this renderer.
Definition at line 67 of file glc_renderer.h.
bool GLC_Renderer::hasCollection () const inline
Return true if this renderer has an attached collection.
Definition at line 63 of file glc_renderer.h.
bool GLC_Renderer::instanceRenderPropertiesIsAvailable (GLC_uint id) const
Return true if the renderProperties of the given instance id is available.
Definition at line 60 of file glc_renderer.cpp.
References m_IdToRenderProperties.
bool GLC_Renderer::isCurrent () const inline
Return true if this renderer is current.
Definition at line 77 of file glc_renderer.h.
GLC_Renderer & GLC_Renderer::operator= (const GLC_Renderer & other)
Assignement operator.
Definition at line 77 of file glc_renderer.cpp.
References m_IdToRenderProperties, and m_pCollection.
const GLC_RenderProperties & GLC_Renderer::renderPropertiesOfInstance (GLC_uint id) const
Return the renderProperties of the given instance id.
Definition at line 65 of file glc_renderer.cpp.
References m_IdToRenderProperties.
void GLC_Renderer::setCollection (GLC_3DViewCollection * pCollection)
Set the collection to use.
Definition at line 89 of file glc_renderer.cpp.
References clear(), and m_pCollection.
void GLC_Renderer::setCurrent ()
Set this renderer the current renderer.
Apply stored renderProperties to the attached collection
Definition at line 98 of file glc_renderer.cpp.
References GLC_3DViewCollection::contains(), GLC_3DViewCollection::instanceHandle(), m_IdToRenderProperties, m_IsCurrent, and m_pCollection.
void GLC_Renderer::unSetCurrent ()
Unset this rendere the current rendere.
Save the render properties of all instance of the scene
Definition at line 117 of file glc_renderer.cpp.
References GLC_Object::id(), GLC_3DViewCollection::instancesHandle(), m_IdToRenderProperties, m_IsCurrent, m_pCollection, and GLC_3DViewInstance::renderPropertiesHandle().
Member Data Documentation
QHash<GLC_uint, GLC_RenderProperties> GLC_Renderer::m_IdToRenderProperties private
Definition at line 120 of file glc_renderer.h.
Referenced by addRenderPropertiesOfInstanceId(), clear(), instanceRenderPropertiesIsAvailable(), operator=(), renderPropertiesOfInstance(), setCurrent(), and unSetCurrent().
bool GLC_Renderer::m_IsCurrent private
Definition at line 122 of file glc_renderer.h.
Referenced by setCurrent(), and unSetCurrent().
GLC_3DViewCollection* GLC_Renderer::m_pCollection private
The 3DView collection attached to this renderer.
Definition at line 118 of file glc_renderer.h.
Referenced by addRenderPropertiesOfInstanceId(), clear(), operator=(), setCollection(), setCurrent(), and unSetCurrent().
The documentation for this class was generated from the following files:
glc_renderer.h
glc_renderer.cpp
©2005-2013 Laurent Ribon