GLC_lib: GLC_3dxmlToWorld Class Reference
GLC_3dxmlToWorld Class Reference
GLC_3dxmlToWorld : Create an GLC_World from 3dxml file.
#include <glc_3dxmltoworld.h>
Classes
struct AssyLink
AssyLink : Assemblage link between parent id and GLC_StructInstance*.
class MaterialRef
MaterialRef : Material reference containing id, name and associated file.
class RepLink
RepLink : Representation link between reference id and representation id.
class V3OccurenceAttrib
V3OccurenceAttrib : Specifique occurence attribute.
struct V4OccurenceAttrib
V3OccurenceAttrib : Specifique occurence attribute.
Signals
void currentQuantum (int)
Public Member Functions
Constructor / Destructor
GLC_3dxmlToWorld ()
Default constructor.
virtual ~GLC_3dxmlToWorld ()
Set Functions
GLC_World * createWorldFrom3dxml (QFile &, bool StructureOnly, bool getExternalRef=false)
Create an GLC_World from an input 3DXML File.
GLC_3DRep create3DrepFrom3dxmlRep (const QString &)
Create 3DRep from an 3DXML rep.
QStringList listOfAttachedFileName () const
Get the list of attached files.
Private Types
typedef QHash< unsigned int,
GLC_StructReference * > ReferenceHash
typedef QHash
< GLC_StructInstance
*, unsigned int > InstanceOfHash
typedef QHash
< GLC_StructInstance
*, QString > InstanceOfExtRefHash
typedef QSet< const QString > SetOfExtRef
typedef QList< AssyLink > AssyLinkList
typedef QList< RepLink > RepLinkList
typedef QHash< const QString,
GLC_StructReference * > ExternalReferenceHash
typedef QHash< const QString,
GLC_Material * > MaterialHash
typedef QHash< const unsigned
int, QString > ReferenceRepHash
Private Member Functions
Private services functions
void loadManifest ()
Load the 3dxml's manifest.
void clear ()
Close all files and clear memmory.
void goToRepId (const QString &)
Go to a Rep of a xml.
void gotToPolygonalRepType ()
Go to Polygonal Rep Type.
QString readAttribute (const QString &, bool required=false)
Read the specified attribute.
void readHeader ()
Read the Header.
void loadProductStructure ()
Load the product structure.
void loadReference3D ()
Load a Reference3D.
void loadInstance3D ()
Load a Instance3D.
void loadReferenceRep ()
Load a Reference representation.
void loadInstanceRep ()
Load a Instance representation.
void loadExternalRef3D ()
Load External Ref.
GLC_StructReference * createReferenceRep (QString id, GLC_3DRep *pRep)
Add a reference from 3dxml to m_ExternalReferenceHash.
GLC_Matrix4x4 loadMatrix (const QString &)
Load Matrix.
void createUnfoldedTree ()
Create the unfolded tree.
void checkForXmlError (const QString &)
void loadFace (GLC_Mesh *, const int lod, double accuracy)
Load a face.
void loadPolyline (GLC_Mesh *)
Load polyline.
void clearMaterialHash ()
Clear material hash.
GLC_Material * loadSurfaceAttributes ()
Load surface attributes.
GLC_Material * getMaterial ()
get material
bool setStreamReaderToFile (QString, bool test=false)
Set the stream reader to the specified file.
void loadDefaultView ()
Load default view element.
void loadV3DefaultViewProperty ()
Load 3DXML V3 default view property.
void loadV4DefaultViewProperty ()
Load 3DXML V4 default view property.
QList< unsigned int > loadOccurencePath ()
Return the occurence path of the current DefaultViewProperty.
void loadGraphicProperties (V4OccurenceAttrib *pAttrib)
Load Graphics properties element.
void loadLocalRepresentations ()
Load the local representation.
void loadExternRepresentations ()
Load the extern representation.
GLC_3DRep loadCurrentExtRep ()
Return the instance of the current extern representation.
void loadCatMaterialRef ()
Load CatMaterial Ref if present.
void loadMaterialDef (const MaterialRef &)
Create material from material def file.
void loadCatRepImage ()
Load CATRepIage if present.
GLC_Texture * loadTexture (QString)
Try to construct a texture with the specified fileName.
void setRepresentationFileName (GLC_3DRep *pRep)
Set fileName of the given 3DRep.
QXmlStreamReader::TokenType readNext ()
Read next element from the stream.
bool goToElement (QXmlStreamReader *pReader, const QString &element)
Go to the given xml Element, return true on succes.
QString getContent (QXmlStreamReader *pReader, const QString &element)
QString readAttribute (QXmlStreamReader *pReader, const QString &attribute)
Read the specified attribute.
bool endElementNotReached (QXmlStreamReader *pReader, const QString &element)
Return true if the end of specified element is not reached.
bool startElementNotReached (QXmlStreamReader *pReader, const QString &element)
Return true if the start of specified element is not reached.
void goToEndElement (QXmlStreamReader *pReader, const QString &element)
Go to the end Element of a xml.
void checkFileValidity (QIODevice *pIODevice)
Check if the given file is binary.
void applyV4Attribute (GLC_StructOccurence *pOccurence, V4OccurenceAttrib *pV4OccurenceAttrib, QHash< GLC_StructInstance *, unsigned int > &InstanceToIdHash)
Apply the given attribute to the right occurence from the given occurence.
void loadRep (GLC_Mesh *pMesh)
Load representation from 3DRep file.
void loadVertexBuffer (GLC_Mesh *pMesh)
Load The 3DXML vertex buffer.
Private Attributes
QXmlStreamReader * m_pStreamReader
Xml Reader.
QString m_FileName
The 3dxml fileName.
QuaZip * m_p3dxmlArchive
The Quazip archive.
QFile * m_pCurrentFile
The current file (if there is no archive)
QString m_RootName
The root Name of the 3dxml file.
GLC_World * m_pWorld
The World to return.
ReferenceHash m_ReferenceHash
Reference Hash Table.
AssyLinkList m_AssyLinkList
The Structure Link Hash Table.
InstanceOfHash m_InstanceOf
Instance of Hash table.
SetOfExtRef m_SetOfExtRef
The set of ext ref to load.
InstanceOfExtRefHash m_InstanceOfExtRefHash
Instance of ext ref hash table.
ExternalReferenceHash m_ExternalReferenceHash
Externam reference hash table.
MaterialHash m_MaterialHash
Hash table of material.
bool m_IsInArchive
Flag to know if the 3dxml is in an archive.
ReferenceRepHash m_ReferenceRepHash
The Reference representation hash table.
RepLinkList m_LocalRepLinkList
The list of local representation link.
RepLinkList m_ExternRepLinkList
The list of extern representation link.
SetOfExtRef m_SetOfExtRep
The set of ext rep to load.
GLC_Material * m_pCurrentMaterial
The 3DREP current material.
QHash< QString, QString > m_TextureImagesHash
The image file hash table.
bool m_LoadStructureOnly
Flag indicate the loading method.
QSet< QString > m_SetOfAttachedFileName
The Set of attached file name.
QString m_CurrentFileName
The current file name.
QDateTime m_CurrentDateTime
The current file time and date.
QHash< unsigned int,
V3OccurenceAttrib * > m_V3OccurenceAttribHash
Hash table of occurence specific attributes for 3DXML V3.
QList< V4OccurenceAttrib * > m_V4OccurenceAttribList
List of occurence specific attributes for 3DXML V4.
bool m_GetExternalRef3DName
bool get external ref 3D name
QList< QByteArray > m_ByteArrayList
bool m_IsVersion3
Flag to know if the 3DXML is in version 3.x.
Static Private Attributes
static QMutex m_ZipMutex
Detailed Description
GLC_3dxmlToWorld : Create an GLC_World from 3dxml file.
Definition at line 52 of file glc_3dxmltoworld.h.
Member Typedef Documentation
typedef QList<AssyLink> GLC_3dxmlToWorld::AssyLinkList private
Definition at line 129 of file glc_3dxmltoworld.h.
typedef QHash<const QString, GLC_StructReference*> GLC_3dxmlToWorld::ExternalReferenceHash private
Definition at line 131 of file glc_3dxmltoworld.h.
typedef QHash<GLC_StructInstance*, QString> GLC_3dxmlToWorld::InstanceOfExtRefHash private
Definition at line 127 of file glc_3dxmltoworld.h.
typedef QHash<GLC_StructInstance*, unsigned int> GLC_3dxmlToWorld::InstanceOfHash private
Definition at line 126 of file glc_3dxmltoworld.h.
typedef QHash<const QString, GLC_Material*> GLC_3dxmlToWorld::MaterialHash private
Definition at line 132 of file glc_3dxmltoworld.h.
typedef QHash<unsigned int, GLC_StructReference*> GLC_3dxmlToWorld::ReferenceHash private
Definition at line 125 of file glc_3dxmltoworld.h.
typedef QHash<const unsigned int, QString> GLC_3dxmlToWorld::ReferenceRepHash private
Definition at line 133 of file glc_3dxmltoworld.h.
typedef QList<RepLink> GLC_3dxmlToWorld::RepLinkList private
Definition at line 130 of file glc_3dxmltoworld.h.
typedef QSet<const QString> GLC_3dxmlToWorld::SetOfExtRef private
Definition at line 128 of file glc_3dxmltoworld.h.
Constructor & Destructor Documentation
GLC_3dxmlToWorld::GLC_3dxmlToWorld ()
Default constructor.
Definition at line 48 of file glc_3dxmltoworld.cpp.
GLC_3dxmlToWorld::~GLC_3dxmlToWorld () virtual
Definition at line 83 of file glc_3dxmltoworld.cpp.
References clearMaterialHash(), m_p3dxmlArchive, m_pCurrentFile, m_pStreamReader, m_V3OccurenceAttribHash, and m_V4OccurenceAttribList.
Member Function Documentation
void GLC_3dxmlToWorld::applyV4Attribute (GLC_StructOccurence * pOccurence, V4OccurenceAttrib * pV4OccurenceAttrib, QHash< GLC_StructInstance *, unsigned int > & InstanceToIdHash) private
Apply the given attribute to the right occurence from the given occurence.
Definition at line 2191 of file glc_3dxmltoworld.cpp.
References GLC_StructOccurence::child(), GLC_StructOccurence::childCount(), GLC_StructOccurence::hasChild(), GLC_3dxmlToWorld::V4OccurenceAttrib::m_IsVisible, GLC_3dxmlToWorld::V4OccurenceAttrib::m_Path, GLC_3dxmlToWorld::V4OccurenceAttrib::m_pMatrix, GLC_3dxmlToWorld::V4OccurenceAttrib::m_pRenderProperties, GLC_StructOccurence::makeFlexible(), GLC_StructOccurence::setRenderProperties(), GLC_StructOccurence::setVisibility(), and GLC_StructOccurence::structInstance().
Referenced by loadProductStructure().
void GLC_3dxmlToWorld::checkFileValidity (QIODevice * pIODevice) private
Check if the given file is binary.
Definition at line 2175 of file glc_3dxmltoworld.cpp.
References clear(), GLC_FileFormatException::FileNotSupported, and m_CurrentFileName.
Referenced by setStreamReaderToFile().
void GLC_3dxmlToWorld::checkForXmlError (const QString & info) private
Check for XML error Throw ecxeption if error occur
Definition at line 1183 of file glc_3dxmltoworld.cpp.
References GLC_ErrorLog::addError(), clear(), m_CurrentFileName, m_FileName, m_pStreamReader, and GLC_FileFormatException::WrongFileFormat.
Referenced by createReferenceRep(), loadCatMaterialRef(), loadCatRepImage(), loadMaterialDef(), loadRep(), loadSurfaceAttributes(), and loadVertexBuffer().
void GLC_3dxmlToWorld::clear () private
Close all files and clear memmory.
Definition at line 286 of file glc_3dxmltoworld.cpp.
References clearMaterialHash(), m_ByteArrayList, m_p3dxmlArchive, m_pCurrentFile, m_pStreamReader, m_pWorld, and m_SetOfAttachedFileName.
Referenced by checkFileValidity(), checkForXmlError(), createReferenceRep(), createWorldFrom3dxml(), loadCurrentExtRep(), loadDefaultView(), loadManifest(), loadOccurencePath(), loadPolyline(), loadProductStructure(), loadReferenceRep(), loadTexture(), loadV3DefaultViewProperty(), loadV4DefaultViewProperty(), loadVertexBuffer(), readAttribute(), readHeader(), and setStreamReaderToFile().
void GLC_3dxmlToWorld::clearMaterialHash () private
Clear material hash.
Definition at line 1324 of file glc_3dxmltoworld.cpp.
References m_MaterialHash.
Referenced by clear(), and ~GLC_3dxmlToWorld().
GLC_3DRep GLC_3dxmlToWorld::create3DrepFrom3dxmlRep (const QString & fileName)
Create 3DRep from an 3DXML rep.
Definition at line 165 of file glc_3dxmltoworld.cpp.
References glc::archiveEntryFileName(), glc::archiveFileName(), GLC_CacheManager::binary3DRep(), GLC_State::cacheIsUsed(), GLC_3DRep::clean(), createReferenceRep(), GLC_State::currentCacheManager(), GLC_StructReference::hasRepresentation(), glc::isArchiveString(), glc::isFileString(), GLC_CacheManager::isUsable(), loadCurrentExtRep(), GLC_BSRep::loadRep(), m_CurrentDateTime, m_CurrentFileName, m_FileName, m_IsInArchive, m_p3dxmlArchive, m_ZipMutex, GLC_StructReference::name(), GLC_StructReference::representationHandle(), GLC_Rep::setName(), setRepresentationFileName(), and setStreamReaderToFile().
Referenced by GLC_Factory::create3DRepFromFile().
GLC_StructReference * GLC_3dxmlToWorld::createReferenceRep (QString id, GLC_3DRep * pRep) private
Add a reference from 3dxml to m_ExternalReferenceHash.
Definition at line 876 of file glc_3dxmltoworld.cpp.
References GLC_ErrorLog::addError(), GLC_3DRep::addGeom(), GLC_CacheManager::addToCache(), GLC_State::cacheIsUsed(), checkForXmlError(), GLC_3DRep::clean(), clear(), GLC_State::currentCacheManager(), endElementNotReached(), GLC_Rep::fileName(), GLC_FileFormatException::FileNotSupported, GLC_Mesh::finish(), goToElement(), goToRepId(), gotToPolygonalRepType(), GLC_3DRep::isEmpty(), loadRep(), m_CurrentDateTime, m_CurrentFileName, m_FileName, m_pStreamReader, readAttribute(), GLC_Rep::setLastModified(), GLC_Rep::setName(), GLC_Geometry::setName(), setRepresentationFileName(), setStreamReaderToFile(), and GLC_FileFormatException::WrongFileFormat.
Referenced by create3DrepFrom3dxmlRep(), loadExternalRef3D(), and loadLocalRepresentations().
void GLC_3dxmlToWorld::createUnfoldedTree () private
Create the unfolded tree.
Definition at line 1068 of file glc_3dxmltoworld.cpp.
References GLC_StructOccurence::addChild(), GLC_ErrorLog::addError(), GLC_StructInstance::firstOccurenceHandle(), GLC_StructReference::hasStructInstance(), GLC_StructInstance::hasStructOccurence(), GLC_StructOccurence::isOrphan(), GLC_StructReference::listOfStructInstances(), GLC_StructInstance::listOfStructOccurences(), m_AssyLinkList, m_FileName, m_pWorld, m_ReferenceHash, GLC_StructOccurence::name(), GLC_StructInstance::name(), GLC_StructReference::name(), GLC_World::rootOccurence(), GLC_StructInstance::setReference(), GLC_StructInstance::structReference(), GLC_StructOccurence::updateChildrenAbsoluteMatrix(), and GLC_World::worldHandle().
Referenced by loadProductStructure().
GLC_World * GLC_3dxmlToWorld::createWorldFrom3dxml (QFile & file, bool StructureOnly, bool getExternalRef = false)
Create an GLC_World from an input 3DXML File.
Definition at line 113 of file glc_3dxmltoworld.cpp.
References clear(), currentQuantum(), loadCatMaterialRef(), loadCatRepImage(), loadManifest(), loadProductStructure(), m_CurrentDateTime, m_FileName, m_GetExternalRef3DName, m_IsInArchive, m_LoadStructureOnly, m_p3dxmlArchive, m_pWorld, m_RootName, and readHeader().
Referenced by GLC_FileLoader::createWorldFromFile(), and GLC_Factory::createWorldStructureFrom3dxml().
void GLC_3dxmlToWorld::currentQuantum (int) signal
Referenced by createWorldFrom3dxml(), loadExternalRef3D(), and loadExternRepresentations().
bool GLC_3dxmlToWorld::endElementNotReached (QXmlStreamReader * pReader, const QString & element) inline private
Return true if the end of specified element is not reached.
Definition at line 453 of file glc_3dxmltoworld.h.
Referenced by createReferenceRep(), getContent(), goToEndElement(), gotToPolygonalRepType(), loadCatMaterialRef(), loadCatRepImage(), loadDefaultView(), loadFace(), loadGraphicProperties(), loadInstance3D(), loadLocalRepresentations(), loadMaterialDef(), loadOccurencePath(), loadProductStructure(), loadReference3D(), loadRep(), loadSurfaceAttributes(), loadV3DefaultViewProperty(), loadV4DefaultViewProperty(), loadVertexBuffer(), and readHeader().
QString GLC_3dxmlToWorld::getContent (QXmlStreamReader * pReader, const QString & element) inline private
Definition at line 433 of file glc_3dxmltoworld.h.
References endElementNotReached(), and readNext().
Referenced by loadInstance3D(), loadInstanceRep(), loadManifest(), loadOccurencePath(), loadV3DefaultViewProperty(), loadV4DefaultViewProperty(), loadVertexBuffer(), and readHeader().
GLC_Material * GLC_3dxmlToWorld::getMaterial () private
get material
Definition at line 1368 of file glc_3dxmltoworld.cpp.
References GLC_Material::hashCode(), m_MaterialHash, readAttribute(), GLC_Material::setAmbientColor(), GLC_Object::setName(), GLC_Material::setOpacity(), GLC_Material::setShininess(), and GLC_Material::setSpecularColor().
Referenced by loadSurfaceAttributes().
bool GLC_3dxmlToWorld::goToElement (QXmlStreamReader * pReader, const QString & element) inline private
Go to the given xml Element, return true on succes.
Definition at line 424 of file glc_3dxmltoworld.h.
References readNext().
Referenced by createReferenceRep(), loadCatMaterialRef(), loadCatRepImage(), loadGraphicProperties(), loadInstance3D(), loadInstanceRep(), loadLocalRepresentations(), loadMaterialDef(), loadProductStructure(), loadV3DefaultViewProperty(), and readHeader().
void GLC_3dxmlToWorld::goToEndElement (QXmlStreamReader * pReader, const QString & element) inline private
Go to the end Element of a xml.
Definition at line 463 of file glc_3dxmltoworld.h.
References endElementNotReached(), and readNext().
void GLC_3dxmlToWorld::goToRepId (const QString & id) private
Go to a Rep of a xml.
Definition at line 317 of file glc_3dxmltoworld.cpp.
References m_pStreamReader, and readNext().
Referenced by createReferenceRep().
void GLC_3dxmlToWorld::gotToPolygonalRepType () private
Go to Polygonal Rep Type.
Definition at line 328 of file glc_3dxmltoworld.cpp.
References endElementNotReached(), m_pStreamReader, and readNext().
Referenced by createReferenceRep(), and loadCurrentExtRep().
QStringList GLC_3dxmlToWorld::listOfAttachedFileName () const inline
Get the list of attached files.
Definition at line 157 of file glc_3dxmltoworld.h.
Referenced by GLC_FileLoader::createWorldFromFile().
void GLC_3dxmlToWorld::loadCatMaterialRef () private
Load CatMaterial Ref if present.
Definition at line 1936 of file glc_3dxmltoworld.cpp.
References checkForXmlError(), endElementNotReached(), goToElement(), loadMaterialDef(), GLC_3dxmlToWorld::MaterialRef::m_AssociatedFile, GLC_3dxmlToWorld::MaterialRef::m_Id, GLC_3dxmlToWorld::MaterialRef::m_Name, m_pStreamReader, readAttribute(), readNext(), and setStreamReaderToFile().
Referenced by createWorldFrom3dxml().
void GLC_3dxmlToWorld::loadCatRepImage () private
Load CATRepIage if present.
Definition at line 2065 of file glc_3dxmltoworld.cpp.
References checkForXmlError(), endElementNotReached(), goToElement(), m_pStreamReader, m_TextureImagesHash, readAttribute(), readNext(), and setStreamReaderToFile().
Referenced by createWorldFrom3dxml().
GLC_3DRep GLC_3dxmlToWorld::loadCurrentExtRep () private
Return the instance of the current extern representation.
Definition at line 1874 of file glc_3dxmltoworld.cpp.
References GLC_3DRep::addGeom(), GLC_CacheManager::addToCache(), GLC_State::cacheIsUsed(), GLC_3DRep::clean(), clear(), GLC_State::currentCacheManager(), GLC_Mesh::finish(), gotToPolygonalRepType(), loadRep(), m_CurrentDateTime, m_FileName, m_pCurrentMaterial, m_pStreamReader, GLC_Rep::setLastModified(), GLC_Rep::setName(), setRepresentationFileName(), and GLC_FileFormatException::WrongFileFormat.
Referenced by create3DrepFrom3dxmlRep(), and loadExternRepresentations().
void GLC_3dxmlToWorld::loadDefaultView () private
Load default view element.
Definition at line 1534 of file glc_3dxmltoworld.cpp.
References clear(), endElementNotReached(), loadV3DefaultViewProperty(), loadV4DefaultViewProperty(), m_FileName, m_IsVersion3, m_pStreamReader, readNext(), and GLC_FileFormatException::WrongFileFormat.
Referenced by loadProductStructure().
void GLC_3dxmlToWorld::loadExternalRef3D () private
Load External Ref.
Definition at line 773 of file glc_3dxmltoworld.cpp.
References GLC_ErrorLog::addError(), glc::archiveEntryFileName(), GLC_CacheManager::binary3DRep(), glc::builtArchiveString(), glc::builtFileString(), GLC_State::cacheIsUsed(), createReferenceRep(), GLC_State::currentCacheManager(), currentQuantum(), GLC_BSRep::loadRep(), m_CurrentDateTime, m_CurrentFileName, m_ExternalReferenceHash, m_FileName, m_GetExternalRef3DName, m_IsInArchive, m_LoadStructureOnly, m_SetOfAttachedFileName, m_SetOfExtRef, GLC_Rep::setFileName(), GLC_StructReference::setName(), setRepresentationFileName(), and setStreamReaderToFile().
Referenced by loadProductStructure().
void GLC_3dxmlToWorld::loadExternRepresentations () private
Load the extern representation.
Definition at line 1764 of file glc_3dxmltoworld.cpp.
References glc::archiveEntryFileName(), GLC_CacheManager::binary3DRep(), glc::builtArchiveString(), glc::builtFileString(), GLC_State::cacheIsUsed(), GLC_3DRep::clean(), GLC_State::currentCacheManager(), currentQuantum(), GLC_StructReference::hasRepresentation(), GLC_3DRep::isEmpty(), loadCurrentExtRep(), GLC_BSRep::loadRep(), m_CurrentDateTime, m_CurrentFileName, m_ExternRepLinkList, m_FileName, m_IsInArchive, m_LoadStructureOnly, m_ReferenceHash, m_ReferenceRepHash, m_SetOfAttachedFileName, GLC_StructReference::name(), GLC_StructReference::representationHandle(), GLC_StructReference::representationName(), GLC_Rep::setFileName(), GLC_StructReference::setRepresentation(), setRepresentationFileName(), GLC_StructReference::setRepresentationName(), setStreamReaderToFile(), and GLC_3DRep::take().
Referenced by loadProductStructure().
void GLC_3dxmlToWorld::loadFace (GLC_Mesh * pMesh, const int lod, double accuracy) private
Load a face.
Definition at line 1200 of file glc_3dxmltoworld.cpp.
References GLC_ErrorLog::addError(), GLC_Mesh::addTriangles(), GLC_Mesh::addTrianglesFan(), GLC_Mesh::addTrianglesStrip(), endElementNotReached(), loadSurfaceAttributes(), m_CurrentFileName, m_pCurrentMaterial, m_pStreamReader, readAttribute(), and readNext().
Referenced by loadRep().
void GLC_3dxmlToWorld::loadGraphicProperties (V4OccurenceAttrib * pAttrib) private
Load Graphics properties element.
Definition at line 1714 of file glc_3dxmltoworld.cpp.
References endElementNotReached(), goToElement(), GLC_3dxmlToWorld::V4OccurenceAttrib::m_IsVisible, GLC_3dxmlToWorld::V4OccurenceAttrib::m_pRenderProperties, m_pStreamReader, glc::OverwriteMaterial, glc::OverwriteTransparency, readAttribute(), readNext(), GLC_Material::setDiffuseColor(), GLC_Material::setOpacity(), GLC_RenderProperties::setOverwriteMaterial(), GLC_RenderProperties::setOverwriteTransparency(), and GLC_RenderProperties::setRenderingMode().
Referenced by loadV4DefaultViewProperty().
void GLC_3dxmlToWorld::loadInstance3D () private
Load a Instance3D.
Definition at line 641 of file glc_3dxmltoworld.cpp.
References endElementNotReached(), getContent(), goToElement(), GLC_Attributes::insert(), GLC_Attributes::isEmpty(), loadMatrix(), m_AssyLinkList, GLC_3dxmlToWorld::AssyLink::m_InstanceId, m_InstanceOf, m_InstanceOfExtRefHash, GLC_3dxmlToWorld::AssyLink::m_ParentRefId, GLC_3dxmlToWorld::AssyLink::m_pChildInstance, m_pStreamReader, m_SetOfExtRef, GLC_StructInstance::move(), readAttribute(), readNext(), and GLC_StructInstance::setAttributes().
Referenced by loadProductStructure().
void GLC_3dxmlToWorld::loadInstanceRep () private
Load a Instance representation.
Definition at line 741 of file glc_3dxmltoworld.cpp.
References getContent(), goToElement(), m_ExternRepLinkList, m_LocalRepLinkList, m_pStreamReader, GLC_3dxmlToWorld::RepLink::m_ReferenceId, and GLC_3dxmlToWorld::RepLink::m_RepId.
Referenced by loadProductStructure().
void GLC_3dxmlToWorld::loadLocalRepresentations () private
Load the local representation.
Definition at line 1492 of file glc_3dxmltoworld.cpp.
References createReferenceRep(), endElementNotReached(), goToElement(), GLC_StructReference::hasRepresentation(), m_LocalRepLinkList, m_pStreamReader, m_ReferenceHash, m_ReferenceRepHash, GLC_StructReference::name(), readAttribute(), readNext(), GLC_StructReference::representationHandle(), GLC_StructReference::setRepresentation(), and GLC_StructReference::setRepresentationName().
Referenced by loadProductStructure().
void GLC_3dxmlToWorld::loadManifest () private
Load the 3dxml's manifest.
Definition at line 268 of file glc_3dxmltoworld.cpp.
References clear(), getContent(), m_FileName, m_pStreamReader, m_RootName, setStreamReaderToFile(), and GLC_FileFormatException::WrongFileFormat.
Referenced by createWorldFrom3dxml().
void GLC_3dxmlToWorld::loadMaterialDef (const MaterialRef & materialRef) private
Create material from material def file.
Definition at line 1981 of file glc_3dxmltoworld.cpp.
References checkForXmlError(), endElementNotReached(), goToElement(), loadTexture(), GLC_3dxmlToWorld::MaterialRef::m_AssociatedFile, GLC_3dxmlToWorld::MaterialRef::m_Id, m_MaterialHash, GLC_3dxmlToWorld::MaterialRef::m_Name, m_pStreamReader, m_TextureImagesHash, readAttribute(), readNext(), GLC_Material::setAmbientColor(), GLC_Material::setDiffuseColor(), GLC_Object::setName(), GLC_Material::setOpacity(), GLC_Material::setShininess(), GLC_Material::setSpecularColor(), and GLC_Material::setTexture().
Referenced by loadCatMaterialRef().
GLC_Matrix4x4 GLC_3dxmlToWorld::loadMatrix (const QString & stringMatrix) private
Load Matrix.
Definition at line 1034 of file glc_3dxmltoworld.cpp.
References GLC_Matrix4x4::optimise().
Referenced by loadInstance3D(), and loadV4DefaultViewProperty().
QList< unsigned int > GLC_3dxmlToWorld::loadOccurencePath () private
Return the occurence path of the current DefaultViewProperty.
Definition at line 1688 of file glc_3dxmltoworld.cpp.
References clear(), endElementNotReached(), getContent(), m_FileName, m_pStreamReader, readNext(), and GLC_FileFormatException::WrongFileFormat.
Referenced by loadV4DefaultViewProperty().
void GLC_3dxmlToWorld::loadPolyline (GLC_Mesh * pMesh) private
Load polyline.
Definition at line 1291 of file glc_3dxmltoworld.cpp.
References GLC_ErrorLog::addError(), GLC_Geometry::addVerticeGroup(), clear(), m_CurrentFileName, m_FileName, readAttribute(), and GLC_FileFormatException::WrongFileFormat.
Referenced by loadRep().
void GLC_3dxmlToWorld::loadProductStructure () private
Load the product structure.
Definition at line 384 of file glc_3dxmltoworld.cpp.
References GLC_ErrorLog::addError(), applyV4Attribute(), clear(), createUnfoldedTree(), endElementNotReached(), goToElement(), GLC_StructReference::hasStructInstance(), GLC_StructInstance::hasStructOccurence(), GLC_StructOccurence::isOrphan(), GLC_World::listOfOccurence(), GLC_StructInstance::listOfStructOccurences(), loadDefaultView(), loadExternalRef3D(), loadExternRepresentations(), loadInstance3D(), loadInstanceRep(), loadLocalRepresentations(), loadReference3D(), loadReferenceRep(), m_AssyLinkList, m_ExternalReferenceHash, m_FileName, GLC_3dxmlToWorld::AssyLink::m_InstanceId, m_InstanceOf, m_InstanceOfExtRefHash, GLC_3dxmlToWorld::V3OccurenceAttrib::m_IsVisible, GLC_3dxmlToWorld::AssyLink::m_pChildInstance, GLC_3dxmlToWorld::V3OccurenceAttrib::m_pRenderProperties, m_pStreamReader, m_pWorld, m_ReferenceHash, m_V3OccurenceAttribHash, m_V4OccurenceAttribList, GLC_StructOccurence::name(), GLC_StructInstance::name(), GLC_StructReference::name(), readNext(), GLC_World::rootOccurence(), GLC_StructInstance::setReference(), GLC_StructOccurence::updateOccurenceNumber(), and GLC_FileFormatException::WrongFileFormat.
Referenced by createWorldFrom3dxml().
void GLC_3dxmlToWorld::loadReference3D () private
Load a Reference3D.
Definition at line 593 of file glc_3dxmltoworld.cpp.
References endElementNotReached(), GLC_Attributes::insert(), GLC_Attributes::isEmpty(), m_FileName, m_pStreamReader, m_pWorld, m_ReferenceHash, readAttribute(), readNext(), GLC_World::rootOccurence(), GLC_StructReference::setAttributes(), GLC_StructReference::setName(), GLC_World::setRootName(), GLC_StructOccurence::structInstance(), and GLC_StructInstance::structReference().
Referenced by loadProductStructure().
void GLC_3dxmlToWorld::loadReferenceRep () private
Load a Reference representation.
Definition at line 708 of file glc_3dxmltoworld.cpp.
References clear(), GLC_FileFormatException::FileNotSupported, m_CurrentFileName, m_FileName, m_ReferenceRepHash, and readAttribute().
Referenced by loadProductStructure().
void GLC_3dxmlToWorld::loadRep (GLC_Mesh * pMesh) private
Load representation from 3DRep file.
Definition at line 2236 of file glc_3dxmltoworld.cpp.
References GLC_ErrorLog::addError(), checkForXmlError(), endElementNotReached(), loadFace(), loadPolyline(), loadSurfaceAttributes(), loadVertexBuffer(), m_FileName, m_pCurrentMaterial, m_pStreamReader, readAttribute(), and readNext().
Referenced by createReferenceRep(), and loadCurrentExtRep().
GLC_Material * GLC_3dxmlToWorld::loadSurfaceAttributes () private
Load surface attributes.
Definition at line 1339 of file glc_3dxmltoworld.cpp.
References checkForXmlError(), endElementNotReached(), getMaterial(), m_MaterialHash, m_pStreamReader, readAttribute(), and readNext().
Referenced by loadFace(), and loadRep().
GLC_Texture * GLC_3dxmlToWorld::loadTexture (QString fileName) private
Try to construct a texture with the specified fileName.
Definition at line 2092 of file glc_3dxmltoworld.cpp.
References GLC_ErrorLog::addError(), glc::builtArchiveString(), clear(), GLC_FileFormatException::FileNotSupported, m_CurrentFileName, m_FileName, m_IsInArchive, m_p3dxmlArchive, and m_SetOfAttachedFileName.
Referenced by loadMaterialDef().
void GLC_3dxmlToWorld::loadV3DefaultViewProperty () private
Load 3DXML V3 default view property.
Definition at line 1567 of file glc_3dxmltoworld.cpp.
References clear(), endElementNotReached(), getContent(), goToElement(), m_FileName, GLC_3dxmlToWorld::V3OccurenceAttrib::m_IsVisible, GLC_3dxmlToWorld::V3OccurenceAttrib::m_pRenderProperties, m_pStreamReader, m_V3OccurenceAttribHash, glc::OverwriteMaterial, glc::OverwriteTransparency, readAttribute(), readNext(), GLC_Material::setDiffuseColor(), GLC_RenderProperties::setOverwriteMaterial(), GLC_RenderProperties::setOverwriteTransparency(), GLC_RenderProperties::setRenderingMode(), and GLC_FileFormatException::WrongFileFormat.
Referenced by loadDefaultView().
void GLC_3dxmlToWorld::loadV4DefaultViewProperty () private
Load 3DXML V4 default view property.
Definition at line 1646 of file glc_3dxmltoworld.cpp.
References clear(), endElementNotReached(), getContent(), loadGraphicProperties(), loadMatrix(), loadOccurencePath(), m_FileName, GLC_3dxmlToWorld::V4OccurenceAttrib::m_Path, GLC_3dxmlToWorld::V4OccurenceAttrib::m_pMatrix, m_pStreamReader, m_V4OccurenceAttribList, readNext(), and GLC_FileFormatException::WrongFileFormat.
Referenced by loadDefaultView().
void GLC_3dxmlToWorld::loadVertexBuffer (GLC_Mesh * pMesh) private
Load The 3DXML vertex buffer.
Definition at line 2325 of file glc_3dxmltoworld.cpp.
References GLC_ErrorLog::addError(), GLC_Mesh::addNormals(), GLC_Mesh::addTexels(), GLC_Mesh::addVertice(), checkForXmlError(), clear(), endElementNotReached(), getContent(), m_CurrentFileName, m_FileName, m_pStreamReader, readNext(), and GLC_FileFormatException::WrongFileFormat.
Referenced by loadRep().
QString GLC_3dxmlToWorld::readAttribute (const QString & name, bool required = false) private
Read the specified attribute.
Definition at line 342 of file glc_3dxmltoworld.cpp.
References clear(), m_FileName, m_pStreamReader, and GLC_FileFormatException::WrongFileFormat.
Referenced by createReferenceRep(), getMaterial(), loadCatMaterialRef(), loadCatRepImage(), loadFace(), loadGraphicProperties(), loadInstance3D(), loadLocalRepresentations(), loadMaterialDef(), loadPolyline(), loadReference3D(), loadReferenceRep(), loadRep(), loadSurfaceAttributes(), and loadV3DefaultViewProperty().
QString GLC_3dxmlToWorld::readAttribute (QXmlStreamReader * pReader, const QString & attribute) inline private
Read the specified attribute.
Definition at line 448 of file glc_3dxmltoworld.h.
void GLC_3dxmlToWorld::readHeader () private
Read the Header.
Definition at line 359 of file glc_3dxmltoworld.cpp.
References clear(), endElementNotReached(), getContent(), goToElement(), m_FileName, m_IsVersion3, m_pStreamReader, m_RootName, readNext(), setStreamReaderToFile(), glc::version(), and GLC_FileFormatException::WrongFileFormat.
Referenced by createWorldFrom3dxml().
QXmlStreamReader::TokenType GLC_3dxmlToWorld::readNext () inline private
Read next element from the stream.
Definition at line 409 of file glc_3dxmltoworld.h.
References m_ByteArrayList, and m_pStreamReader.
Referenced by getContent(), goToElement(), goToEndElement(), goToRepId(), gotToPolygonalRepType(), loadCatMaterialRef(), loadCatRepImage(), loadDefaultView(), loadFace(), loadGraphicProperties(), loadInstance3D(), loadLocalRepresentations(), loadMaterialDef(), loadOccurencePath(), loadProductStructure(), loadReference3D(), loadRep(), loadSurfaceAttributes(), loadV3DefaultViewProperty(), loadV4DefaultViewProperty(), loadVertexBuffer(), and readHeader().
void GLC_3dxmlToWorld::setRepresentationFileName (GLC_3DRep * pRep) private
Set fileName of the given 3DRep.
Definition at line 2163 of file glc_3dxmltoworld.cpp.
References glc::builtArchiveString(), m_CurrentFileName, m_FileName, m_IsInArchive, and GLC_Rep::setFileName().
Referenced by create3DrepFrom3dxmlRep(), createReferenceRep(), loadCurrentExtRep(), loadExternalRef3D(), and loadExternRepresentations().
bool GLC_3dxmlToWorld::setStreamReaderToFile (QString fileName, bool test = false) private
Set the stream reader to the specified file.
Definition at line 1404 of file glc_3dxmltoworld.cpp.
References GLC_ErrorLog::addError(), checkFileValidity(), chunckSize, clear(), GLC_FileFormatException::FileNotSupported, m_ByteArrayList, m_CurrentDateTime, m_CurrentFileName, m_FileName, m_IsInArchive, m_p3dxmlArchive, m_pCurrentFile, m_pStreamReader, m_SetOfAttachedFileName, m_ZipMutex, and GLC_FileFormatException::WrongFileFormat.
Referenced by create3DrepFrom3dxmlRep(), createReferenceRep(), loadCatMaterialRef(), loadCatRepImage(), loadExternalRef3D(), loadExternRepresentations(), loadManifest(), and readHeader().
bool GLC_3dxmlToWorld::startElementNotReached (QXmlStreamReader * pReader, const QString & element) inline private
Return true if the start of specified element is not reached.
Definition at line 458 of file glc_3dxmltoworld.h.
Member Data Documentation
AssyLinkList GLC_3dxmlToWorld::m_AssyLinkList private
The Structure Link Hash Table.
Definition at line 341 of file glc_3dxmltoworld.h.
Referenced by createUnfoldedTree(), loadInstance3D(), and loadProductStructure().
QList<QByteArray> GLC_3dxmlToWorld::m_ByteArrayList private
Definition at line 402 of file glc_3dxmltoworld.h.
Referenced by clear(), readNext(), and setStreamReaderToFile().
QDateTime GLC_3dxmlToWorld::m_CurrentDateTime private
The current file time and date.
Definition at line 389 of file glc_3dxmltoworld.h.
Referenced by create3DrepFrom3dxmlRep(), createReferenceRep(), createWorldFrom3dxml(), loadCurrentExtRep(), loadExternalRef3D(), loadExternRepresentations(), and setStreamReaderToFile().
QString GLC_3dxmlToWorld::m_CurrentFileName private
The current file name.
Definition at line 386 of file glc_3dxmltoworld.h.
Referenced by checkFileValidity(), checkForXmlError(), create3DrepFrom3dxmlRep(), createReferenceRep(), loadExternalRef3D(), loadExternRepresentations(), loadFace(), loadPolyline(), loadReferenceRep(), loadTexture(), loadVertexBuffer(), setRepresentationFileName(), and setStreamReaderToFile().
ExternalReferenceHash GLC_3dxmlToWorld::m_ExternalReferenceHash private
Externam reference hash table.
Definition at line 353 of file glc_3dxmltoworld.h.
Referenced by loadExternalRef3D(), and loadProductStructure().
RepLinkList GLC_3dxmlToWorld::m_ExternRepLinkList private
The list of extern representation link.
Definition at line 368 of file glc_3dxmltoworld.h.
Referenced by loadExternRepresentations(), and loadInstanceRep().
QString GLC_3dxmlToWorld::m_FileName private
The 3dxml fileName.
Definition at line 323 of file glc_3dxmltoworld.h.
Referenced by checkForXmlError(), create3DrepFrom3dxmlRep(), createReferenceRep(), createUnfoldedTree(), createWorldFrom3dxml(), loadCurrentExtRep(), loadDefaultView(), loadExternalRef3D(), loadExternRepresentations(), loadManifest(), loadOccurencePath(), loadPolyline(), loadProductStructure(), loadReference3D(), loadReferenceRep(), loadRep(), loadTexture(), loadV3DefaultViewProperty(), loadV4DefaultViewProperty(), loadVertexBuffer(), readAttribute(), readHeader(), setRepresentationFileName(), and setStreamReaderToFile().
bool GLC_3dxmlToWorld::m_GetExternalRef3DName private
bool get external ref 3D name
Definition at line 398 of file glc_3dxmltoworld.h.
Referenced by createWorldFrom3dxml(), and loadExternalRef3D().
InstanceOfHash GLC_3dxmlToWorld::m_InstanceOf private
Instance of Hash table.
Definition at line 344 of file glc_3dxmltoworld.h.
Referenced by loadInstance3D(), and loadProductStructure().
InstanceOfExtRefHash GLC_3dxmlToWorld::m_InstanceOfExtRefHash private
Instance of ext ref hash table.
Definition at line 350 of file glc_3dxmltoworld.h.
Referenced by loadInstance3D(), and loadProductStructure().
bool GLC_3dxmlToWorld::m_IsInArchive private
Flag to know if the 3dxml is in an archive.
Definition at line 359 of file glc_3dxmltoworld.h.
Referenced by create3DrepFrom3dxmlRep(), createWorldFrom3dxml(), loadExternalRef3D(), loadExternRepresentations(), loadTexture(), setRepresentationFileName(), and setStreamReaderToFile().
bool GLC_3dxmlToWorld::m_IsVersion3 private
Flag to know if the 3DXML is in version 3.x.
Definition at line 405 of file glc_3dxmltoworld.h.
Referenced by loadDefaultView(), and readHeader().
bool GLC_3dxmlToWorld::m_LoadStructureOnly private
Flag indicate the loading method.
Definition at line 380 of file glc_3dxmltoworld.h.
Referenced by createWorldFrom3dxml(), loadExternalRef3D(), and loadExternRepresentations().
RepLinkList GLC_3dxmlToWorld::m_LocalRepLinkList private
The list of local representation link.
Definition at line 365 of file glc_3dxmltoworld.h.
Referenced by loadInstanceRep(), and loadLocalRepresentations().
MaterialHash GLC_3dxmlToWorld::m_MaterialHash private
Hash table of material.
Definition at line 356 of file glc_3dxmltoworld.h.
Referenced by clearMaterialHash(), getMaterial(), loadMaterialDef(), and loadSurfaceAttributes().
QuaZip* GLC_3dxmlToWorld::m_p3dxmlArchive private
The Quazip archive.
Definition at line 326 of file glc_3dxmltoworld.h.
Referenced by clear(), create3DrepFrom3dxmlRep(), createWorldFrom3dxml(), loadTexture(), setStreamReaderToFile(), and ~GLC_3dxmlToWorld().
QFile* GLC_3dxmlToWorld::m_pCurrentFile private
The current file (if there is no archive)
Definition at line 329 of file glc_3dxmltoworld.h.
Referenced by clear(), setStreamReaderToFile(), and ~GLC_3dxmlToWorld().
GLC_Material* GLC_3dxmlToWorld::m_pCurrentMaterial private
The 3DREP current material.
Definition at line 374 of file glc_3dxmltoworld.h.
Referenced by loadCurrentExtRep(), loadFace(), and loadRep().
QXmlStreamReader* GLC_3dxmlToWorld::m_pStreamReader private
Xml Reader.
Definition at line 320 of file glc_3dxmltoworld.h.
Referenced by checkForXmlError(), clear(), createReferenceRep(), goToRepId(), gotToPolygonalRepType(), loadCatMaterialRef(), loadCatRepImage(), loadCurrentExtRep(), loadDefaultView(), loadFace(), loadGraphicProperties(), loadInstance3D(), loadInstanceRep(), loadLocalRepresentations(), loadManifest(), loadMaterialDef(), loadOccurencePath(), loadProductStructure(), loadReference3D(), loadRep(), loadSurfaceAttributes(), loadV3DefaultViewProperty(), loadV4DefaultViewProperty(), loadVertexBuffer(), readAttribute(), readHeader(), readNext(), setStreamReaderToFile(), and ~GLC_3dxmlToWorld().
GLC_World* GLC_3dxmlToWorld::m_pWorld private
The World to return.
Definition at line 335 of file glc_3dxmltoworld.h.
Referenced by clear(), createUnfoldedTree(), createWorldFrom3dxml(), loadProductStructure(), and loadReference3D().
ReferenceHash GLC_3dxmlToWorld::m_ReferenceHash private
Reference Hash Table.
Definition at line 338 of file glc_3dxmltoworld.h.
Referenced by createUnfoldedTree(), loadExternRepresentations(), loadLocalRepresentations(), loadProductStructure(), and loadReference3D().
ReferenceRepHash GLC_3dxmlToWorld::m_ReferenceRepHash private
The Reference representation hash table.
Definition at line 362 of file glc_3dxmltoworld.h.
Referenced by loadExternRepresentations(), loadLocalRepresentations(), and loadReferenceRep().
QString GLC_3dxmlToWorld::m_RootName private
The root Name of the 3dxml file.
Definition at line 332 of file glc_3dxmltoworld.h.
Referenced by createWorldFrom3dxml(), loadManifest(), and readHeader().
QSet<QString> GLC_3dxmlToWorld::m_SetOfAttachedFileName private
The Set of attached file name.
Definition at line 383 of file glc_3dxmltoworld.h.
Referenced by clear(), loadExternalRef3D(), loadExternRepresentations(), loadTexture(), and setStreamReaderToFile().
SetOfExtRef GLC_3dxmlToWorld::m_SetOfExtRef private
The set of ext ref to load.
Definition at line 347 of file glc_3dxmltoworld.h.
Referenced by loadExternalRef3D(), and loadInstance3D().
SetOfExtRef GLC_3dxmlToWorld::m_SetOfExtRep private
The set of ext rep to load.
Definition at line 371 of file glc_3dxmltoworld.h.
QHash<QString, QString> GLC_3dxmlToWorld::m_TextureImagesHash private
The image file hash table.
Definition at line 377 of file glc_3dxmltoworld.h.
Referenced by loadCatRepImage(), and loadMaterialDef().
QHash<unsigned int, V3OccurenceAttrib*> GLC_3dxmlToWorld::m_V3OccurenceAttribHash private
Hash table of occurence specific attributes for 3DXML V3.
Definition at line 392 of file glc_3dxmltoworld.h.
Referenced by loadProductStructure(), loadV3DefaultViewProperty(), and ~GLC_3dxmlToWorld().
QList<V4OccurenceAttrib*> GLC_3dxmlToWorld::m_V4OccurenceAttribList private
List of occurence specific attributes for 3DXML V4.
Definition at line 395 of file glc_3dxmltoworld.h.
Referenced by loadProductStructure(), loadV4DefaultViewProperty(), and ~GLC_3dxmlToWorld().
QMutex GLC_3dxmlToWorld::m_ZipMutex static private
Definition at line 400 of file glc_3dxmltoworld.h.
Referenced by create3DrepFrom3dxmlRep(), and setStreamReaderToFile().
The documentation for this class was generated from the following files:
glc_3dxmltoworld.h
glc_3dxmltoworld.cpp
©2005-2013 Laurent Ribon