GLC_lib: GLC_RepTrackBallMover Class Reference
GLC_RepTrackBallMover Class Reference
GLC_RepTrackBallMover : Track Ball representation.
#include <glc_reptrackballmover.h>
Public Member Functions
GLC_RepTrackBallMover (GLC_Viewport *)
Default constructor.
GLC_RepTrackBallMover (const GLC_RepTrackBallMover &)
Copy constructor.
virtual ~GLC_RepTrackBallMover ()
Get Functions
virtual GLC_RepMover * clone () const
Return a clone of the repmover.
Set Functions
virtual void init ()
Set Arcs orientation and position in concordance with mouse position.
virtual void update ()
Set Arcs position in concordance with mouse position.
virtual void setMainColor (const QColor &color)
Set representation main color.
void setRatio (double ratio)
Set representation screen ration.
OpenGL Functions
virtual void glDraw ()
Virtual interface for OpenGL Geometry set up.
Public Member Functions inherited from GLC_RepMover
GLC_RepMover (GLC_Viewport *)
Default constructor.
GLC_RepMover (const GLC_RepMover &)
Copy constructor.
virtual ~GLC_RepMover ()
Destructor.
QColor mainColor ()
Return the main Color.
virtual void setThickness (double thickness)
Set representation wire thickness.
void setRepMoverInfo (RepMoverInfo *pRepMoverInfo)
Set the repMoverInfo of this rep.
void render ()
Representation OpenGL Execution.
Private Member Functions
void computeRadius ()
Compute trackball radius.
Private Attributes
double m_Radius
trackball radius
GLC_Circle m_MainCircle
Main Circle.
GLC_3DViewInstance m_Arc1
Arc 1 showing orbit sphere orientation.
GLC_Matrix4x4 m_MatArc1
Arc 1 positionning Matrix.
GLC_3DViewInstance m_Arc2
Arc 2 showing orbit sphere orientation.
GLC_Matrix4x4 m_MatArc2
Arc 2 positionning Matrix.
double m_Ratio
The ratio of the trackball size.
Additional Inherited Members
Protected Member Functions inherited from GLC_RepMover
Protected Attributes inherited from GLC_RepMover
GLC_Viewport * m_pViewport
The viewport.
QColor m_MainColor
The rep main color.
double m_Thickness
The rep wire thickness.
GLC_RenderProperties m_RenderProperties
The rep rendering properties.
RepMoverInfo * m_pRepMoverInfo
The repmover info of this rep.
Detailed Description
GLC_RepTrackBallMover : Track Ball representation.
Definition at line 37 of file glc_reptrackballmover.h.
Constructor & Destructor Documentation
GLC_RepTrackBallMover::GLC_RepTrackBallMover (GLC_Viewport * pViewport)
Default constructor.
Definition at line 35 of file glc_reptrackballmover.cpp.
References ARCANGLE, GLC_3DViewInstance::geomAt(), m_Arc1, m_Arc2, m_MainCircle, GLC_RepMover::m_MainColor, m_MatArc1, m_MatArc2, glc::PI, GLC_Matrix4x4::setMatRot(), GLC_Geometry::setWireColor(), glc::Y_AXIS(), and glc::Z_AXIS().
Referenced by clone().
GLC_RepTrackBallMover::GLC_RepTrackBallMover (const GLC_RepTrackBallMover & repMover)
Copy constructor.
Definition at line 64 of file glc_reptrackballmover.cpp.
GLC_RepTrackBallMover::~GLC_RepTrackBallMover () virtual
Definition at line 77 of file glc_reptrackballmover.cpp.
Member Function Documentation
GLC_RepMover * GLC_RepTrackBallMover::clone () const virtual
Return a clone of the repmover.
Implements GLC_RepMover.
Definition at line 88 of file glc_reptrackballmover.cpp.
References GLC_RepTrackBallMover().
void GLC_RepTrackBallMover::computeRadius () private
Compute trackball radius.
Definition at line 199 of file glc_reptrackballmover.cpp.
References GLC_3DViewInstance::geomAt(), m_Arc1, m_Arc2, m_MainCircle, GLC_RepMover::m_pViewport, m_Radius, m_Ratio, GLC_Circle::setRadius(), GLC_Viewport::viewHSize(), and GLC_Viewport::viewVSize().
Referenced by glDraw().
void GLC_RepTrackBallMover::glDraw () virtual
Virtual interface for OpenGL Geometry set up.
Implements GLC_RepMover.
Definition at line 154 of file glc_reptrackballmover.cpp.
References computeRadius(), GLC_Context::current(), GLC_Context::glcLoadIdentity(), GLC_Context::glcMatrixMode(), GLC_Context::glcOrtho(), GLC_Context::glcPopMatrix(), GLC_Context::glcPushMatrix(), m_Arc1, m_Arc2, m_MainCircle, GLC_RepMover::m_pViewport, GLC_RepMover::m_RenderProperties, GLC_Geometry::render(), GLC_3DViewInstance::render(), GLC_RenderProperties::setRenderingFlag(), glc::TransparentRenderFlag, GLC_Viewport::viewHSize(), GLC_Viewport::viewVSize(), and glc::WireRenderFlag.
void GLC_RepTrackBallMover::init () virtual
Set Arcs orientation and position in concordance with mouse position.
Reimplemented from GLC_RepMover.
Definition at line 98 of file glc_reptrackballmover.cpp.
References m_Arc1, m_Arc2, m_MatArc1, m_MatArc2, GLC_RepMover::RepMoverInfo::m_MatrixInfo, GLC_RepMover::m_pRepMoverInfo, GLC_RepMover::RepMoverInfo::m_VectorInfo, GLC_Vector3d::setLength(), GLC_3DViewInstance::setMatrix(), GLC_Matrix4x4::setMatRot(), GLC_Vector3d::setZ(), and glc::Z_AXIS().
void GLC_RepTrackBallMover::setMainColor (const QColor & color) virtual
Set representation main color.
Reimplemented from GLC_RepMover.
Definition at line 141 of file glc_reptrackballmover.cpp.
References GLC_3DViewInstance::geomAt(), m_Arc1, m_Arc2, m_MainCircle, GLC_RepMover::m_MainColor, GLC_RepMover::setMainColor(), and GLC_Geometry::setWireColor().
void GLC_RepTrackBallMover::setRatio (double ratio) inline
Set representation screen ration.
Definition at line 74 of file glc_reptrackballmover.h.
Referenced by GLC_TrackBallMover::setRatio().
void GLC_RepTrackBallMover::update () virtual
Set Arcs position in concordance with mouse position.
Reimplemented from GLC_RepMover.
Definition at line 131 of file glc_reptrackballmover.cpp.
References m_Arc1, m_Arc2, GLC_RepMover::RepMoverInfo::m_MatrixInfo, GLC_RepMover::m_pRepMoverInfo, and GLC_3DViewInstance::multMatrix().
Member Data Documentation
GLC_3DViewInstance GLC_RepTrackBallMover::m_Arc1 private
Arc 1 showing orbit sphere orientation.
Definition at line 105 of file glc_reptrackballmover.h.
Referenced by computeRadius(), GLC_RepTrackBallMover(), glDraw(), init(), setMainColor(), and update().
GLC_3DViewInstance GLC_RepTrackBallMover::m_Arc2 private
Arc 2 showing orbit sphere orientation.
Definition at line 109 of file glc_reptrackballmover.h.
Referenced by computeRadius(), GLC_RepTrackBallMover(), glDraw(), init(), setMainColor(), and update().
GLC_Circle GLC_RepTrackBallMover::m_MainCircle private
Main Circle.
Definition at line 103 of file glc_reptrackballmover.h.
Referenced by computeRadius(), GLC_RepTrackBallMover(), glDraw(), and setMainColor().
GLC_Matrix4x4 GLC_RepTrackBallMover::m_MatArc1 private
Arc 1 positionning Matrix.
Definition at line 107 of file glc_reptrackballmover.h.
Referenced by GLC_RepTrackBallMover(), and init().
GLC_Matrix4x4 GLC_RepTrackBallMover::m_MatArc2 private
Arc 2 positionning Matrix.
Definition at line 111 of file glc_reptrackballmover.h.
Referenced by GLC_RepTrackBallMover(), and init().
double GLC_RepTrackBallMover::m_Radius private
trackball radius
Definition at line 101 of file glc_reptrackballmover.h.
Referenced by computeRadius().
double GLC_RepTrackBallMover::m_Ratio private
The ratio of the trackball size.
Definition at line 113 of file glc_reptrackballmover.h.
Referenced by computeRadius().
The documentation for this class was generated from the following files:
glc_reptrackballmover.h
glc_reptrackballmover.cpp
©2005-2013 Laurent Ribon