GLC_lib: GLC_StlToWorld Class Reference
GLC_StlToWorld Class Reference
GLC_StlToWorld : Create an GLC_World from stl file.
#include <glc_stltoworld.h>
Signals
void currentQuantum (int)
Public Member Functions
Constructor / Destructor
GLC_StlToWorld ()
virtual ~GLC_StlToWorld ()
Set Functions
GLC_World * CreateWorldFromStl (QFile &file)
Create and return an GLC_World* from an input STL File.
Private Member Functions
Private services functions
void clear ()
clear stlToWorld allocate memmory
void scanFacet ()
Scan a line previously extracted from STL file.
GLC_Vector3df extract3dVect (QString &)
Extract a 3D Vector from a string.
void LoadBinariStl (QFile &)
Load Binarie STL File.
Private Attributes
GLC_World * m_pWorld
pointer to a GLC_World
QString m_FileName
The Stl File name.
int m_CurrentLineNumber
The current line number.
QTextStream m_StlStream
The Text Stream.
GLC_Mesh * m_pCurrentMesh
The current mesh.
IndexList m_CurrentFace
Current face index.
QList< float > m_VertexBulk
Vertex Bulk data.
QList< float > m_NormalBulk
Normal Bulk data.
GLuint m_CurrentIndex
The current index.
Detailed Description
GLC_StlToWorld : Create an GLC_World from stl file.
An GLC_StlToWorld extract the only mesh from an .stl file
List of elements extracted from the STL
Vertex
Face
Normal coordinate
Definition at line 53 of file glc_stltoworld.h.
Constructor & Destructor Documentation
GLC_StlToWorld::GLC_StlToWorld ()
Definition at line 37 of file glc_stltoworld.cpp.
GLC_StlToWorld::~GLC_StlToWorld () virtual
Definition at line 52 of file glc_stltoworld.cpp.
References clear().
Member Function Documentation
void GLC_StlToWorld::clear () private
clear stlToWorld allocate memmory
Definition at line 164 of file glc_stltoworld.cpp.
References m_CurrentFace, m_CurrentLineNumber, m_FileName, m_pCurrentMesh, and m_pWorld.
Referenced by CreateWorldFromStl(), extract3dVect(), LoadBinariStl(), scanFacet(), and ~GLC_StlToWorld().
GLC_World * GLC_StlToWorld::CreateWorldFromStl (QFile & file)
Create and return an GLC_World* from an input STL File.
Definition at line 62 of file glc_stltoworld.cpp.
References GLC_StructOccurence::addChild(), GLC_Mesh::addNormals(), GLC_Mesh::addTriangles(), GLC_Mesh::addVertice(), clear(), currentQuantum(), GLC_FileFormatException::FileNotFound, GLC_Mesh::finish(), LoadBinariStl(), m_CurrentFace, m_CurrentLineNumber, m_FileName, m_NormalBulk, m_pCurrentMesh, m_pWorld, m_StlStream, m_VertexBulk, GLC_World::rootOccurence(), scanFacet(), and GLC_Geometry::setName().
Referenced by GLC_FileLoader::createWorldFromFile().
void GLC_StlToWorld::currentQuantum (int) signal
Referenced by CreateWorldFromStl(), and LoadBinariStl().
GLC_Vector3df GLC_StlToWorld::extract3dVect (QString & line) private
Extract a 3D Vector from a string.
Definition at line 310 of file glc_stltoworld.cpp.
References clear(), m_CurrentLineNumber, m_FileName, GLC_Vector3df::setVect(), and GLC_FileFormatException::WrongFileFormat.
Referenced by scanFacet().
void GLC_StlToWorld::LoadBinariStl (QFile & file) private
Load Binarie STL File.
Definition at line 346 of file glc_stltoworld.cpp.
References clear(), currentQuantum(), m_CurrentFace, m_CurrentIndex, m_FileName, m_NormalBulk, m_VertexBulk, and GLC_FileFormatException::WrongFileFormat.
Referenced by CreateWorldFromStl().
void GLC_StlToWorld::scanFacet () private
Scan a line previously extracted from STL file.
Definition at line 179 of file glc_stltoworld.cpp.
References GLC_StructOccurence::addChild(), GLC_Mesh::addNormals(), GLC_Mesh::addTriangles(), GLC_Mesh::addVertice(), clear(), extract3dVect(), GLC_Mesh::finish(), m_CurrentFace, m_CurrentIndex, m_CurrentLineNumber, m_FileName, m_NormalBulk, m_pCurrentMesh, m_pWorld, m_StlStream, m_VertexBulk, GLC_World::rootOccurence(), GLC_Geometry::setName(), GLC_FileFormatException::WrongFileFormat, GLC_Vector3df::x(), GLC_Vector3df::y(), and GLC_Vector3df::z().
Referenced by CreateWorldFromStl().
Member Data Documentation
IndexList GLC_StlToWorld::m_CurrentFace private
Current face index.
Definition at line 117 of file glc_stltoworld.h.
Referenced by clear(), CreateWorldFromStl(), LoadBinariStl(), and scanFacet().
GLuint GLC_StlToWorld::m_CurrentIndex private
The current index.
Definition at line 126 of file glc_stltoworld.h.
Referenced by LoadBinariStl(), and scanFacet().
int GLC_StlToWorld::m_CurrentLineNumber private
The current line number.
Definition at line 108 of file glc_stltoworld.h.
Referenced by clear(), CreateWorldFromStl(), extract3dVect(), and scanFacet().
QString GLC_StlToWorld::m_FileName private
The Stl File name.
Definition at line 105 of file glc_stltoworld.h.
Referenced by clear(), CreateWorldFromStl(), extract3dVect(), LoadBinariStl(), and scanFacet().
QList<float> GLC_StlToWorld::m_NormalBulk private
Normal Bulk data.
Definition at line 123 of file glc_stltoworld.h.
Referenced by CreateWorldFromStl(), LoadBinariStl(), and scanFacet().
GLC_Mesh* GLC_StlToWorld::m_pCurrentMesh private
The current mesh.
Definition at line 114 of file glc_stltoworld.h.
Referenced by clear(), CreateWorldFromStl(), and scanFacet().
GLC_World* GLC_StlToWorld::m_pWorld private
pointer to a GLC_World
Definition at line 102 of file glc_stltoworld.h.
Referenced by clear(), CreateWorldFromStl(), and scanFacet().
QTextStream GLC_StlToWorld::m_StlStream private
The Text Stream.
Definition at line 111 of file glc_stltoworld.h.
Referenced by CreateWorldFromStl(), and scanFacet().
QList<float> GLC_StlToWorld::m_VertexBulk private
Vertex Bulk data.
Definition at line 120 of file glc_stltoworld.h.
Referenced by CreateWorldFromStl(), LoadBinariStl(), and scanFacet().
The documentation for this class was generated from the following files:
glc_stltoworld.h
glc_stltoworld.cpp
©2005-2013 Laurent Ribon