GLC_lib: GLC_RotationManipulator Class Reference
GLC_RotationManipulator Class Reference
GLC_RotationManipulator :
#include <glc_rotationmanipulator.h>
Public Member Functions
Constructor / Destructor
GLC_RotationManipulator (GLC_Viewport *pViewport, const GLC_Line3d &rotationLine)
Construct a rotation manipulator with the given viewport and rotation line.
GLC_RotationManipulator (const GLC_RotationManipulator &rotationmanipulator)
Copy constructor.
virtual ~GLC_RotationManipulator ()
Destructor.
Get Functions
virtual GLC_AbstractManipulator * clone () const
Clone the concrete manipulator.
GLC_Line3d rotationLine () const
Return the rotation line of this rotation manipulator.
Set Functions
void setRotationLine (const GLC_Line3d line)
Set the rotation line of this rotation manipulator.
Public Member Functions inherited from GLC_AbstractManipulator
GLC_AbstractManipulator (GLC_Viewport *pViewport)
Construct an abstract manipulator with the given viewport.
GLC_AbstractManipulator (const GLC_AbstractManipulator &abstractManipulator)
Copy constructor.
virtual ~GLC_AbstractManipulator ()
Destructor.
bool isInManipulateState () const
Return true if this manipulator is in manipulate state.
const GLC_Point3d & previousPosition () const
Return a const reference on the previous position.
GLC_Viewport * viewportHandle () const
Return the viewport of this manipulator.
void enterManipulateState (const GLC_Point3d &startPoint)
Put this manipulator in manipulate state.
GLC_Matrix4x4 manipulate (const GLC_Point3d &newPoint)
Manipulate this manipulator and return the moving matrix.
void exitManipulateState ()
Exit this manipulator of manipulate state.
void setViewport (GLC_Viewport *pViewport)
Set the viewport of this manipulator.
Protected Member Functions
virtual GLC_Matrix4x4 doManipulate (const GLC_Point3d &newPoint, const GLC_Vector3d &projectionDirection)
Manipulate this manipulator and return the moving matrix.
Private Attributes
GLC_Line3d m_RotationLine
The rotation line of this manipulator.
Additional Inherited Members
Protected Attributes inherited from GLC_AbstractManipulator
GLC_Viewport * m_pViewport
The viewport associated with this manipulator.
GLC_Plane m_SliddingPlane
The currentSlidding plane.
GLC_Point3d m_PreviousPosition
The previous position.
bool m_IsInManipulateState
Flag to know if this manipulator is in manipulate state.
Detailed Description
GLC_RotationManipulator :
GLC_RotationManipulator
Definition at line 39 of file glc_rotationmanipulator.h.
Constructor & Destructor Documentation
GLC_RotationManipulator::GLC_RotationManipulator (GLC_Viewport * pViewport, const GLC_Line3d & rotationLine)
Construct a rotation manipulator with the given viewport and rotation line.
Definition at line 27 of file glc_rotationmanipulator.cpp.
Referenced by clone().
GLC_RotationManipulator::GLC_RotationManipulator (const GLC_RotationManipulator & rotationmanipulator)
Copy constructor.
Definition at line 34 of file glc_rotationmanipulator.cpp.
GLC_RotationManipulator::~GLC_RotationManipulator () virtual
Destructor.
Definition at line 41 of file glc_rotationmanipulator.cpp.
Member Function Documentation
GLC_AbstractManipulator * GLC_RotationManipulator::clone () const virtual
Clone the concrete manipulator.
Implements GLC_AbstractManipulator.
Definition at line 46 of file glc_rotationmanipulator.cpp.
References GLC_RotationManipulator().
GLC_Matrix4x4 GLC_RotationManipulator::doManipulate (const GLC_Point3d & newPoint, const GLC_Vector3d & projectionDirection) protected virtual
Manipulate this manipulator and return the moving matrix.
Implements GLC_AbstractManipulator.
Definition at line 51 of file glc_rotationmanipulator.cpp.
References GLC_Line3d::direction(), glc::lineIntersectPlane(), GLC_AbstractManipulator::m_PreviousPosition, m_RotationLine, normalize(), and GLC_Line3d::startingPoint().
GLC_Line3d GLC_RotationManipulator::rotationLine () const inline
Return the rotation line of this rotation manipulator.
Definition at line 66 of file glc_rotationmanipulator.h.
void GLC_RotationManipulator::setRotationLine (const GLC_Line3d line) inline
Set the rotation line of this rotation manipulator.
Definition at line 77 of file glc_rotationmanipulator.h.
Member Data Documentation
GLC_Line3d GLC_RotationManipulator::m_RotationLine private
The rotation line of this manipulator.
Definition at line 94 of file glc_rotationmanipulator.h.
Referenced by doManipulate().
The documentation for this class was generated from the following files:
glc_rotationmanipulator.h
glc_rotationmanipulator.cpp
©2005-2013 Laurent Ribon