GLC_lib: GLC_ImagePlane Class Reference
GLC_ImagePlane Class Reference
GLC_ImagePlane : Viewport background image.
#include <glc_imageplane.h>
Public Member Functions
Constructor / Destructor
GLC_ImagePlane (const QString &ImageName)
Construct image plane from the given image file name and QGLContext.
GLC_ImagePlane (const QImage &image)
Construct image plane from the given image and QGLContext.
~GLC_ImagePlane ()
OpenGL Functions
void render ()
Render this image plane.
Private Attributes
GLC_3DViewInstance m_Representation
The image representation.
Detailed Description
GLC_ImagePlane : Viewport background image.
An GLC_ImagePlane is just a plane with a image texture.
Definition at line 40 of file glc_imageplane.h.
Constructor & Destructor Documentation
GLC_ImagePlane::GLC_ImagePlane (const QString & ImageName)
Construct image plane from the given image file name and QGLContext.
Definition at line 35 of file glc_imageplane.cpp.
References GLC_Geometry::addMaterial(), GLC_Factory::createTexture(), GLC_3DViewInstance::geomAt(), GLC_Texture::imageOfTexture(), GLC_Factory::instance(), m_Representation, and GLC_Texture::setMaxTextureSize().
GLC_ImagePlane::GLC_ImagePlane (const QImage & image)
Construct image plane from the given image and QGLContext.
Definition at line 43 of file glc_imageplane.cpp.
References GLC_Geometry::addMaterial(), GLC_Factory::createTexture(), GLC_3DViewInstance::geomAt(), GLC_Factory::instance(), m_Representation, and GLC_Texture::setMaxTextureSize().
GLC_ImagePlane::~GLC_ImagePlane ()
Definition at line 51 of file glc_imageplane.cpp.
Member Function Documentation
void GLC_ImagePlane::render ()
Render this image plane.
Definition at line 60 of file glc_imageplane.cpp.
References GLC_Context::current(), GLC_Context::glcLoadIdentity(), GLC_Context::glcMatrixMode(), GLC_Context::glcOrtho(), GLC_Context::glcPopMatrix(), GLC_Context::glcPushMatrix(), m_Representation, and GLC_3DViewInstance::render().
Referenced by GLC_Viewport::renderImagePlane().
Member Data Documentation
GLC_3DViewInstance GLC_ImagePlane::m_Representation private
The image representation.
Definition at line 72 of file glc_imageplane.h.
Referenced by GLC_ImagePlane(), and render().
The documentation for this class was generated from the following files:
glc_imageplane.h
glc_imageplane.cpp
©2005-2013 Laurent Ribon