GLC_lib: GLC_UniformShaderData Class Reference
GLC_UniformShaderData Class Reference
#include <glc_uniformshaderdata.h>
Public Member Functions
GLC_UniformShaderData ()
virtual ~GLC_UniformShaderData ()
Set Functions
void setLightValues (const GLC_Light &light)
Set Light values from the given light.
void setLightingState (bool enable)
Set lighting enbale state.
void setModelViewProjectionMatrix (const GLC_Matrix4x4 &modelView, const GLC_Matrix4x4 &projection)
Set the model view matrix.
void updateAll (const GLC_Context *pContext)
Update all uniform variables.
Detailed Description
Definition at line 36 of file glc_uniformshaderdata.h.
Constructor & Destructor Documentation
GLC_UniformShaderData::GLC_UniformShaderData ()
Definition at line 31 of file glc_uniformshaderdata.cpp.
GLC_UniformShaderData::~GLC_UniformShaderData () virtual
Definition at line 37 of file glc_uniformshaderdata.cpp.
Member Function Documentation
void GLC_UniformShaderData::setLightingState (bool enable)
Set lighting enbale state.
Definition at line 50 of file glc_uniformshaderdata.cpp.
Referenced by GLC_Context::glcEnableLighting(), and updateAll().
void GLC_UniformShaderData::setLightValues (const GLC_Light & light)
Set Light values from the given light.
Definition at line 45 of file glc_uniformshaderdata.cpp.
void GLC_UniformShaderData::setModelViewProjectionMatrix (const GLC_Matrix4x4 & modelView, const GLC_Matrix4x4 & projection)
Set the model view matrix.
Definition at line 56 of file glc_uniformshaderdata.cpp.
Referenced by GLC_Context::glcLoadIdentity(), GLC_Context::glcLoadMatrix(), GLC_Context::glcMultMatrix(), and updateAll().
void GLC_UniformShaderData::updateAll (const GLC_Context * pContext)
Update all uniform variables.
Definition at line 97 of file glc_uniformshaderdata.cpp.
References GLC_Context::lightingIsEnable(), GLC_Context::modelViewMatrix(), GLC_Context::projectionMatrix(), setLightingState(), and setModelViewProjectionMatrix().
The documentation for this class was generated from the following files:
glc_uniformshaderdata.h
glc_uniformshaderdata.cpp
©2005-2013 Laurent Ribon