GLC_lib: GLC_State Class Reference
GLC_State Class Reference
GLC_State store GLC_lib state.
#include <glc_state.h>
Public Member Functions
~GLC_State ()
Static Public Member Functions
Get Functions
static bool vboSupported ()
Return true if VBO is supported.
static bool vboUsed ()
Return true if VBO is used.
static bool glslSupported ()
Return true if GLSL is supported.
static bool frameBufferSupported ()
Return true if frameBuffer is supported.
static bool glslUsed ()
Return true if GLSL is used.
static bool pointSpriteSupported ()
Return true if Point Sprite is supported.
static bool selectionShaderUsed ()
Return true if selection shader is used.
static bool isInSelectionMode ()
Return true if is in selection mode.
static QString version ()
Return the Opengl version.
static QString vendor ()
Return the Opengl vendor.
static QString renderer ()
Return the Opengl renderer.
static bool vendorIsNvidia ()
Return true if OpenGL Vendor is NVIDIA.
static bool isPixelCullingActivated ()
Return true if pixel culling is activate.
static bool cacheIsUsed ()
Return true if the cache is used.
static GLC_CacheManager & currentCacheManager ()
Return the current cache manager.
static bool isSpacePartitionningActivated ()
Return true if space partitionning is used.
static int defaultOctreeDepth ()
Return the default octree depth.
static bool isFrustumCullingActivated ()
Return true if frustum culling is activated.
static bool isValid ()
Return true valid.
Set Functions
static void init ()
Intialize the state.
static void setVboSupport ()
Set VBO support.
static void setVboUsage (const bool)
Set VBO usage.
static void setGlslSupport ()
Set GLSL support.
static void setPointSpriteSupport ()
Set Point Sprite support.
static void setFrameBufferSupport ()
Set the frame buffer support.
static void setGlslUsage (const bool)
Set GLSL usage.
static void setSelectionShaderUsage (const bool)
Set selection shader usage.
static void setSelectionMode (const bool)
Set selection mode.
static void setPixelCullingUsage (const bool)
Set pixel culling state.
static void setCacheUsage (const bool)
Set the cache usage.
static void setCurrentCacheManager (const GLC_CacheManager &)
Set the current cache manager.
static void setSpacePartionningUsage (const bool)
Set space partionning usage.
static void setDefaultOctreeDepth (int)
Set the default octree depth.
static void setFrustumCullingUsage (bool)
Set the frustum culling usage.
Private Member Functions
GLC_State ()
Static Private Attributes
static bool m_VboSupported = false
VBO supported flag.
static bool m_UseVbo = true
VBO used.
static bool m_GlslSupported = false
GLSL supported flag.
static bool m_PointSpriteSupported = false
Point Sprite supported flag.
static bool m_UseShader = true
Use shader.
static bool m_UseSelectionShader = false
Use selectionShader flag.
static bool m_IsInSelectionMode = false
In selection mode.
static bool m_IsPixelCullingActivated = true
Pixel culling activation.
static QString m_Version
The Opengl card version.
static QString m_Vendor
The Opengl card vendor.
static QString m_Renderer
The Opengl card renderer.
static bool m_UseCache = false
Cache usage.
static GLC_CacheManager m_CacheManager
The current cache manager.
static bool m_IsSpacePartitionningActivated = false
Space partitionning activation.
static bool m_IsFrustumCullingActivated = false
Frustum culling activated.
static bool m_IsFrameBufferSupported = false
Frame buffer supported.
static bool m_IsValid = false
State valid flag.
Detailed Description
GLC_State store GLC_lib state.
GLC_State is used to set and get glabal GLC_lib state
Definition at line 41 of file glc_state.h.
Constructor & Destructor Documentation
GLC_State::GLC_State () private
GLC_State::~GLC_State ()
Definition at line 53 of file glc_state.cpp.
Member Function Documentation
bool GLC_State::cacheIsUsed () static
Return true if the cache is used.
Definition at line 122 of file glc_state.cpp.
References m_UseCache.
GLC_CacheManager & GLC_State::currentCacheManager () static
Return the current cache manager.
Definition at line 127 of file glc_state.cpp.
References m_CacheManager.
int GLC_State::defaultOctreeDepth () static
Return the default octree depth.
Definition at line 137 of file glc_state.cpp.
bool GLC_State::frameBufferSupported () static
Return true if frameBuffer is supported.
Definition at line 72 of file glc_state.cpp.
References m_IsFrameBufferSupported.
bool GLC_State::glslSupported () static
Return true if GLSL is supported.
Definition at line 67 of file glc_state.cpp.
References m_GlslSupported.
bool GLC_State::glslUsed () static
Return true if GLSL is used.
Definition at line 77 of file glc_state.cpp.
References m_GlslSupported, and m_UseShader.
void GLC_State::init () static
Intialize the state.
Definition at line 147 of file glc_state.cpp.
References isValid(), m_IsValid, m_Renderer, m_Vendor, m_Version, setFrameBufferSupport(), setGlslSupport(), setPointSpriteSupport(), and setVboSupport().
Referenced by GLC_Context::makeCurrent().
bool GLC_State::isFrustumCullingActivated () static
Return true if frustum culling is activated.
Definition at line 142 of file glc_state.cpp.
References m_IsFrustumCullingActivated.
bool GLC_State::isInSelectionMode () static
Return true if is in selection mode.
Definition at line 92 of file glc_state.cpp.
References m_IsInSelectionMode.
bool GLC_State::isPixelCullingActivated () static
Return true if pixel culling is activate.
Definition at line 117 of file glc_state.cpp.
References m_IsPixelCullingActivated.
bool GLC_State::isSpacePartitionningActivated () static
Return true if space partitionning is used.
Definition at line 132 of file glc_state.cpp.
References m_IsSpacePartitionningActivated.
bool GLC_State::isValid () static
Return true valid.
Definition at line 164 of file glc_state.cpp.
References m_IsValid.
Referenced by init(), and GLC_Context::makeCurrent().
bool GLC_State::pointSpriteSupported () static
Return true if Point Sprite is supported.
Definition at line 82 of file glc_state.cpp.
References m_PointSpriteSupported.
QString GLC_State::renderer () static
Return the Opengl renderer.
Definition at line 107 of file glc_state.cpp.
References m_Renderer.
bool GLC_State::selectionShaderUsed () static
Return true if selection shader is used.
Definition at line 87 of file glc_state.cpp.
References m_UseSelectionShader.
void GLC_State::setCacheUsage (const bool cacheUsage) static
Set the cache usage.
Definition at line 216 of file glc_state.cpp.
References m_UseCache.
void GLC_State::setCurrentCacheManager (const GLC_CacheManager & cacheManager) static
Set the current cache manager.
Definition at line 221 of file glc_state.cpp.
References m_CacheManager.
void GLC_State::setDefaultOctreeDepth (int depth) static
Set the default octree depth.
Definition at line 231 of file glc_state.cpp.
void GLC_State::setFrameBufferSupport () static
Set the frame buffer support.
Definition at line 191 of file glc_state.cpp.
References m_IsFrameBufferSupported.
Referenced by init().
void GLC_State::setFrustumCullingUsage (bool usage) static
Set the frustum culling usage.
Definition at line 236 of file glc_state.cpp.
References m_IsFrustumCullingActivated.
void GLC_State::setGlslSupport () static
Set GLSL support.
Definition at line 180 of file glc_state.cpp.
References glc::extensionIsSupported(), glc::loadGlSlExtension(), m_GlslSupported, m_UseShader, and setGlslUsage().
Referenced by init().
void GLC_State::setGlslUsage (const bool glslUsage) static
Set GLSL usage.
Definition at line 196 of file glc_state.cpp.
References m_GlslSupported, and m_UseShader.
Referenced by setGlslSupport().
void GLC_State::setPixelCullingUsage (const bool activation) static
Set pixel culling state.
Definition at line 211 of file glc_state.cpp.
References m_IsPixelCullingActivated.
void GLC_State::setPointSpriteSupport () static
Set Point Sprite support.
Definition at line 186 of file glc_state.cpp.
References glc::extensionIsSupported(), glc::loadPointSpriteExtension(), and m_PointSpriteSupported.
Referenced by init().
void GLC_State::setSelectionMode (const bool mode) static
Set selection mode.
Definition at line 206 of file glc_state.cpp.
References m_IsInSelectionMode.
void GLC_State::setSelectionShaderUsage (const bool shaderUsed) static
Set selection shader usage.
Definition at line 201 of file glc_state.cpp.
References m_GlslSupported, and m_UseSelectionShader.
void GLC_State::setSpacePartionningUsage (const bool usage) static
Set space partionning usage.
Definition at line 226 of file glc_state.cpp.
References m_IsSpacePartitionningActivated.
void GLC_State::setVboSupport () static
Set VBO support.
Definition at line 169 of file glc_state.cpp.
References glc::extensionIsSupported(), glc::loadVboExtension(), m_UseVbo, m_VboSupported, and setVboUsage().
Referenced by init().
void GLC_State::setVboUsage (const bool vboUsed) static
Set VBO usage.
Definition at line 175 of file glc_state.cpp.
References m_UseVbo, m_VboSupported, and vboUsed().
Referenced by setVboSupport().
bool GLC_State::vboSupported () static
Return true if VBO is supported.
Definition at line 57 of file glc_state.cpp.
References m_VboSupported.
bool GLC_State::vboUsed () static
Return true if VBO is used.
Definition at line 62 of file glc_state.cpp.
References m_UseVbo.
Referenced by setVboUsage().
QString GLC_State::vendor () static
Return the Opengl vendor.
Definition at line 102 of file glc_state.cpp.
References m_Vendor.
bool GLC_State::vendorIsNvidia () static
Return true if OpenGL Vendor is NVIDIA.
Definition at line 112 of file glc_state.cpp.
References m_Vendor.
QString GLC_State::version () static
Return the Opengl version.
Definition at line 97 of file glc_state.cpp.
References m_Version.
Member Data Documentation
GLC_CacheManager GLC_State::m_CacheManager static private
The current cache manager.
Definition at line 204 of file glc_state.h.
Referenced by currentCacheManager(), and setCurrentCacheManager().
bool GLC_State::m_GlslSupported = false static private
GLSL supported flag.
Definition at line 174 of file glc_state.h.
Referenced by glslSupported(), glslUsed(), setGlslSupport(), setGlslUsage(), and setSelectionShaderUsage().
bool GLC_State::m_IsFrameBufferSupported = false static private
Frame buffer supported.
Definition at line 213 of file glc_state.h.
Referenced by frameBufferSupported(), and setFrameBufferSupport().
bool GLC_State::m_IsFrustumCullingActivated = false static private
Frustum culling activated.
Definition at line 210 of file glc_state.h.
Referenced by isFrustumCullingActivated(), and setFrustumCullingUsage().
bool GLC_State::m_IsInSelectionMode = false static private
In selection mode.
Definition at line 186 of file glc_state.h.
Referenced by isInSelectionMode(), and setSelectionMode().
bool GLC_State::m_IsPixelCullingActivated = true static private
Pixel culling activation.
Definition at line 189 of file glc_state.h.
Referenced by isPixelCullingActivated(), and setPixelCullingUsage().
bool GLC_State::m_IsSpacePartitionningActivated = false static private
Space partitionning activation.
Definition at line 207 of file glc_state.h.
Referenced by isSpacePartitionningActivated(), and setSpacePartionningUsage().
bool GLC_State::m_IsValid = false static private
State valid flag.
Definition at line 216 of file glc_state.h.
Referenced by init(), and isValid().
bool GLC_State::m_PointSpriteSupported = false static private
Point Sprite supported flag.
Definition at line 177 of file glc_state.h.
Referenced by pointSpriteSupported(), and setPointSpriteSupport().
QString GLC_State::m_Renderer static private
The Opengl card renderer.
Definition at line 198 of file glc_state.h.
Referenced by init(), and renderer().
bool GLC_State::m_UseCache = false static private
Cache usage.
Definition at line 201 of file glc_state.h.
Referenced by cacheIsUsed(), and setCacheUsage().
bool GLC_State::m_UseSelectionShader = false static private
Use selectionShader flag.
Definition at line 183 of file glc_state.h.
Referenced by selectionShaderUsed(), and setSelectionShaderUsage().
bool GLC_State::m_UseShader = true static private
Use shader.
Definition at line 180 of file glc_state.h.
Referenced by glslUsed(), setGlslSupport(), and setGlslUsage().
bool GLC_State::m_UseVbo = true static private
VBO used.
Definition at line 171 of file glc_state.h.
Referenced by setVboSupport(), setVboUsage(), and vboUsed().
bool GLC_State::m_VboSupported = false static private
VBO supported flag.
Definition at line 168 of file glc_state.h.
Referenced by setVboSupport(), setVboUsage(), and vboSupported().
QString GLC_State::m_Vendor static private
The Opengl card vendor.
Definition at line 195 of file glc_state.h.
Referenced by init(), vendor(), and vendorIsNvidia().
QString GLC_State::m_Version static private
The Opengl card version.
Definition at line 192 of file glc_state.h.
Referenced by init(), and version().
The documentation for this class was generated from the following files:
glc_state.h
glc_state.cpp
©2005-2013 Laurent Ribon