GLC_lib: GLC_3DWidgetManager Class Reference
GLC_3DWidgetManager Class Reference
#include <glc_3dwidgetmanager.h>
Public Member Functions
Constructor / Destructor
GLC_3DWidgetManager (GLC_Viewport *pViewport)
Construct the 3d widget manager associted to the given Viewport.
GLC_3DWidgetManager (const GLC_3DWidgetManager &widgetManager)
Construct a 3d widget manager from the given 3D widget manager.
~GLC_3DWidgetManager ()
Destructor.
Get Functions
GLC_BoundingBox boundingBox ()
Return the boundingBox of 3dwidget.
bool contains3DWidget (GLC_uint id) const
Return true if this manager contains the given widget id.
GLC_3DWidget * widget (GLC_uint id) const
Return the 3DWidget of the given widget id.
bool isEmpty () const
Return true if this 3DWidget manager is empty.
Set Functions
void add3DWidget (GLC_3DWidget *p3DWidget)
Add the given 3D widget into this manager.
void remove3DWidget (GLC_uint id)
Remove the 3D widget with the given id from this manager.
void clear ()
Clear all widget from this manager.
void setWidgetVisible (GLC_uint id, bool visible)
Set the visibility of the given 3D widget id.
Interaction Functions
glc::WidgetEventFlag mouseDoubleClickEvent (QMouseEvent *pEvent)
Recieve Mouse double click event with the given instance id Return true if the event is catch.
glc::WidgetEventFlag mouseMoveEvent (QMouseEvent *pEvent)
Recieve Mouse move event with the given instance id Return true if the event is catch.
glc::WidgetEventFlag mousePressEvent (QMouseEvent *pEvent)
Recieve Mouse press event with the given instance id Return true if the event is catch.
glc::WidgetEventFlag mouseReleaseEvent (QMouseEvent *pEvent)
Recieve Mouse release event with the given instance id Return true if the event is catch.
OpenGL Functions
void render ()
Render the 3DWidget of this manager.
Private Attributes
GLC_3DWidgetManagerHandle * m_pWidgetManagerHandle
The widget manager handle.
Detailed Description
Definition at line 33 of file glc_3dwidgetmanager.h.
Constructor & Destructor Documentation
GLC_3DWidgetManager::GLC_3DWidgetManager (GLC_Viewport * pViewport)
Construct the 3d widget manager associted to the given Viewport.
Definition at line 26 of file glc_3dwidgetmanager.cpp.
GLC_3DWidgetManager::GLC_3DWidgetManager (const GLC_3DWidgetManager & widgetManager)
Construct a 3d widget manager from the given 3D widget manager.
Definition at line 32 of file glc_3dwidgetmanager.cpp.
References GLC_3DWidgetManagerHandle::increment(), and m_pWidgetManagerHandle.
GLC_3DWidgetManager::~GLC_3DWidgetManager ()
Destructor.
Definition at line 38 of file glc_3dwidgetmanager.cpp.
References GLC_3DWidgetManagerHandle::decrement(), GLC_3DWidgetManagerHandle::isOrphan(), and m_pWidgetManagerHandle.
Member Function Documentation
void GLC_3DWidgetManager::add3DWidget (GLC_3DWidget * p3DWidget) inline
Add the given 3D widget into this manager.
Definition at line 81 of file glc_3dwidgetmanager.h.
GLC_BoundingBox GLC_3DWidgetManager::boundingBox (void) inline
Return the boundingBox of 3dwidget.
Definition at line 58 of file glc_3dwidgetmanager.h.
void GLC_3DWidgetManager::clear (void) inline
Clear all widget from this manager.
Definition at line 90 of file glc_3dwidgetmanager.h.
bool GLC_3DWidgetManager::contains3DWidget (GLC_uint id) const inline
Return true if this manager contains the given widget id.
Definition at line 62 of file glc_3dwidgetmanager.h.
bool GLC_3DWidgetManager::isEmpty (void) const inline
Return true if this 3DWidget manager is empty.
Definition at line 70 of file glc_3dwidgetmanager.h.
References GLC_3DWidget::isEmpty().
glc::WidgetEventFlag GLC_3DWidgetManager::mouseDoubleClickEvent (QMouseEvent * pEvent) inline
Recieve Mouse double click event with the given instance id Return true if the event is catch.
Definition at line 104 of file glc_3dwidgetmanager.h.
glc::WidgetEventFlag GLC_3DWidgetManager::mouseMoveEvent (QMouseEvent * pEvent) inline
Recieve Mouse move event with the given instance id Return true if the event is catch.
Definition at line 108 of file glc_3dwidgetmanager.h.
glc::WidgetEventFlag GLC_3DWidgetManager::mousePressEvent (QMouseEvent * pEvent) inline
Recieve Mouse press event with the given instance id Return true if the event is catch.
Definition at line 112 of file glc_3dwidgetmanager.h.
glc::WidgetEventFlag GLC_3DWidgetManager::mouseReleaseEvent (QMouseEvent * pEvent) inline
Recieve Mouse release event with the given instance id Return true if the event is catch.
Definition at line 116 of file glc_3dwidgetmanager.h.
void GLC_3DWidgetManager::remove3DWidget (GLC_uint id) inline
Remove the 3D widget with the given id from this manager.
Associated 3D view instance are removed
Definition at line 86 of file glc_3dwidgetmanager.h.
void GLC_3DWidgetManager::render () inline
Render the 3DWidget of this manager.
Definition at line 127 of file glc_3dwidgetmanager.h.
void GLC_3DWidgetManager::setWidgetVisible (GLC_uint id, bool visible) inline
Set the visibility of the given 3D widget id.
Definition at line 94 of file glc_3dwidgetmanager.h.
GLC_3DWidget* GLC_3DWidgetManager::widget (GLC_uint id) const inline
Return the 3DWidget of the given widget id.
Definition at line 66 of file glc_3dwidgetmanager.h.
Member Data Documentation
GLC_3DWidgetManagerHandle* GLC_3DWidgetManager::m_pWidgetManagerHandle private
The widget manager handle.
Definition at line 137 of file glc_3dwidgetmanager.h.
Referenced by GLC_3DWidgetManager(), and ~GLC_3DWidgetManager().
The documentation for this class was generated from the following files:
glc_3dwidgetmanager.h
glc_3dwidgetmanager.cpp
©2005-2013 Laurent Ribon