GLC_lib: GLC_Rep Class Reference
GLC_Rep Class Reference abstract
GLC_Rep : Abstract class for a reference represention.
#include <glc_rep.h>
Public Types
enum Type { GLC_VBOGEOM = 1 }
Public Member Functions
Constructor / Destructor
GLC_Rep ()
Default constructor.
GLC_Rep (const GLC_Rep &)
Copy constructor.
virtual GLC_Rep & operator= (const GLC_Rep &)
Assignement operator.
virtual GLC_Rep * clone () const =0
Clone the representation.
virtual GLC_Rep * deepCopy () const =0
Return a deep copy of the representation.
virtual ~GLC_Rep ()
Destructor.
Get Functions
bool isTheLast () const
Return true if the representation is the last.
bool operator== (const GLC_Rep &rep)
Return true if representations are equals.
QString fileName () const
Return the representation file name.
virtual int type () const =0
Return the type of representation.
QString name () const
Return the name of the rep.
virtual bool isEmpty () const =0
Return true if the representation is empty.
bool isLoaded () const
Return true if the representation as been loaded.
QDateTime lastModified () const
Return the rep file las modified date and time.
Set Functions
void setFileName (const QString &fileName)
Set the representation FileName.
void setName (const QString &name)
Set the representation Name.
virtual bool load ()=0
Load the representation.
virtual bool unload ()=0
UnLoad the representation.
virtual void replace (GLC_Rep *)=0
Replace the representation.
void setLastModified (const QDateTime &dateTime)
Set the last modified date and time.
Protected Attributes
bool * m_pIsLoaded
Flag to know if the representation has been loaded.
Private Member Functions
void clear ()
Clear current representation.
Private Attributes
int * m_pNumberOfRepresentation
Number of this representation.
QString * m_pFileName
The File Name of this representation.
QString * m_pName
The Name of the rep.
QDateTime * m_pDateTime
The Date and time of the rep.
Detailed Description
GLC_Rep : Abstract class for a reference represention.
Definition at line 34 of file glc_rep.h.
Member Enumeration Documentation
enum GLC_Rep::Type
Enumerator
GLC_VBOGEOM
Definition at line 37 of file glc_rep.h.
Constructor & Destructor Documentation
GLC_Rep::GLC_Rep ()
Default constructor.
Definition at line 27 of file glc_rep.cpp.
GLC_Rep::GLC_Rep (const GLC_Rep & rep)
Copy constructor.
Definition at line 38 of file glc_rep.cpp.
GLC_Rep::~GLC_Rep () virtual
Destructor.
Definition at line 67 of file glc_rep.cpp.
References clear().
Member Function Documentation
void GLC_Rep::clear () private
Clear current representation.
Definition at line 78 of file glc_rep.cpp.
References m_pDateTime, m_pFileName, m_pIsLoaded, m_pName, and m_pNumberOfRepresentation.
Referenced by operator=(), and ~GLC_Rep().
virtual GLC_Rep* GLC_Rep::clone () const pure virtual
Clone the representation.
Implemented in GLC_3DRep.
Referenced by GLC_StructReference::GLC_StructReference(), and GLC_StructReference::operator=().
virtual GLC_Rep* GLC_Rep::deepCopy () const pure virtual
Return a deep copy of the representation.
Implemented in GLC_3DRep.
QString GLC_Rep::fileName () const inline
Return the representation file name.
Definition at line 82 of file glc_rep.h.
Referenced by GLC_CacheManager::addToCache(), GLC_3dxmlToWorld::createReferenceRep(), GLC_3DRep::deepCopy(), GLC_3DRep::load(), GLC_3DRep::replace(), GLC_WorldTo3dxml::representationFileName(), GLC_StructReference::representationFileName(), and GLC_3DRep::unload().
virtual bool GLC_Rep::isEmpty () const pure virtual
Return true if the representation is empty.
Implemented in GLC_3DRep.
Referenced by GLC_StructReference::representationIsEmpty().
bool GLC_Rep::isLoaded () const inline
Return true if the representation as been loaded.
Definition at line 96 of file glc_rep.h.
Referenced by GLC_StructReference::representationIsLoaded(), and GLC_StructReference::setRepresentation().
bool GLC_Rep::isTheLast () const inline
Return true if the representation is the last.
Definition at line 72 of file glc_rep.h.
Referenced by GLC_3DRep::operator=(), and GLC_3DRep::~GLC_3DRep().
QDateTime GLC_Rep::lastModified () const inline
Return the rep file las modified date and time.
Definition at line 100 of file glc_rep.h.
Referenced by GLC_BSRep::save().
virtual bool GLC_Rep::load () pure virtual
Load the representation.
Implemented in GLC_3DRep.
Referenced by GLC_StructReference::loadRepresentation().
QString GLC_Rep::name () const inline
Return the name of the rep.
Definition at line 89 of file glc_rep.h.
Referenced by GLC_3dsToWorld::createMeshes(), GLC_ColladaToWorld::createOccurenceFromNode(), GLC_3DRep::deepCopy(), GLC_3DViewInstance::GLC_3DViewInstance(), GLC_3DRep::load(), operator<<(), GLC_3DRep::replace(), GLC_WorldTo3dxml::representationFileName(), GLC_StructReference::representationName(), GLC_WorldTo3dxml::writeInstanceRep(), and GLC_WorldTo3dxml::writeReferenceRep().
GLC_Rep & GLC_Rep::operator= (const GLC_Rep & rep) virtual
Assignement operator.
Reimplemented in GLC_3DRep.
Definition at line 49 of file glc_rep.cpp.
References clear(), m_pDateTime, m_pFileName, m_pIsLoaded, m_pName, and m_pNumberOfRepresentation.
Referenced by GLC_3DRep::operator=().
bool GLC_Rep::operator== (const GLC_Rep & rep) inline
Return true if representations are equals.
Definition at line 76 of file glc_rep.h.
References m_pNumberOfRepresentation.
virtual void GLC_Rep::replace (GLC_Rep *) pure virtual
Replace the representation.
Implemented in GLC_3DRep.
void GLC_Rep::setFileName (const QString & fileName) inline
Set the representation FileName.
Definition at line 111 of file glc_rep.h.
Referenced by GLC_3DRep::deepCopy(), GLC_3dxmlToWorld::loadExternalRef3D(), GLC_3dxmlToWorld::loadExternRepresentations(), GLC_BSRep::loadRep(), GLC_3DRep::replace(), and GLC_3dxmlToWorld::setRepresentationFileName().
void GLC_Rep::setLastModified (const QDateTime & dateTime) inline
Set the last modified date and time.
Definition at line 128 of file glc_rep.h.
Referenced by GLC_3dxmlToWorld::createReferenceRep(), and GLC_3dxmlToWorld::loadCurrentExtRep().
void GLC_Rep::setName (const QString & name) inline
Set the representation Name.
Definition at line 115 of file glc_rep.h.
Referenced by GLC_3dxmlToWorld::create3DrepFrom3dxmlRep(), GLC_3dxmlToWorld::createReferenceRep(), GLC_3DRep::deepCopy(), GLC_3DRep::GLC_3DRep(), GLC_3dxmlToWorld::loadCurrentExtRep(), operator>>(), GLC_3DRep::replace(), and GLC_StructReference::setRepresentationName().
virtual int GLC_Rep::type () const pure virtual
Return the type of representation.
Implemented in GLC_3DRep.
virtual bool GLC_Rep::unload () pure virtual
UnLoad the representation.
Implemented in GLC_3DRep.
Referenced by GLC_StructReference::unloadRepresentation().
Member Data Documentation
QDateTime* GLC_Rep::m_pDateTime private
The Date and time of the rep.
Definition at line 161 of file glc_rep.h.
Referenced by clear(), and operator=().
QString* GLC_Rep::m_pFileName private
The File Name of this representation.
Definition at line 155 of file glc_rep.h.
Referenced by clear(), and operator=().
bool* GLC_Rep::m_pIsLoaded protected
Flag to know if the representation has been loaded.
Definition at line 144 of file glc_rep.h.
Referenced by clear(), GLC_3DRep::GLC_3DRep(), GLC_3DRep::load(), and operator=().
QString* GLC_Rep::m_pName private
The Name of the rep.
Definition at line 158 of file glc_rep.h.
Referenced by clear(), and operator=().
int* GLC_Rep::m_pNumberOfRepresentation private
Number of this representation.
Definition at line 152 of file glc_rep.h.
Referenced by clear(), operator=(), and operator==().
The documentation for this class was generated from the following files:
glc_rep.h
glc_rep.cpp
©2005-2013 Laurent Ribon