GLC_lib: GLC_StructOccurence Class Reference
GLC_StructOccurence Class Reference
GLC_StructOccurence : A scene graph occurence node.
#include <glc_structoccurence.h>
Public Member Functions
Constructor / Destructor
GLC_StructOccurence ()
Default constructor.
GLC_StructOccurence (GLC_StructInstance *pStructInstance, GLC_WorldHandle *pWorldHandle=NULL, GLuint shaderId=0)
Create Occurence of the specified instance.
GLC_StructOccurence (GLC_StructInstance *pStructInstance, GLC_uint id, GLC_WorldHandle *pWorldHandle=NULL, GLuint shaderId=0)
Create Occurence of the specified instance and Uid.
GLC_StructOccurence (GLC_3DRep *pRep)
Construct Occurence with the specified GLC_3DRep.
GLC_StructOccurence (GLC_3DRep *pRep, GLC_uint id)
Construct Occurence from the given GLC_3DRep and Uid.
GLC_StructOccurence (GLC_WorldHandle *, const GLC_StructOccurence &, bool shareInstance)
Copy constructor.
virtual ~GLC_StructOccurence ()
Destructor.
Set Functions
void setName (const QString name)
Set Occurence instance Name.
GLC_StructOccurence * updateAbsoluteMatrix ()
Update the absolute matrix.
GLC_StructOccurence * updateChildrenAbsoluteMatrix ()
Update children obsolute Matrix.
void addChild (GLC_StructOccurence *)
Add Child.
void insertChild (int index, GLC_StructOccurence *pChild)
insert Child at the given position
GLC_StructOccurence * addChild (GLC_StructInstance *)
Add Child instance and returns the newly created occurence.
GLC_StructOccurence * insertChild (int index, GLC_StructInstance *pInstance)
Insert Child instance and returns the newly created occurence.
void makeOrphan ()
make the occurence orphan
bool removeChild (GLC_StructOccurence *pChild)
Remove the specified child.
void reverseNormals ()
Reverse Normals of this Occurence and childs.
bool create3DViewInstance (GLuint shaderId=0)
Create the 3DViewInstance of this occurence if there is a valid 3DRep.
bool remove3DViewInstance ()
Remove the 3DViewInstance of this occurence.
void setWorldHandle (GLC_WorldHandle *)
Set this occurence world Handle.
bool loadRepresentation ()
Load the representation and return true if success.
bool unloadRepresentation ()
UnLoad the representation and return true if success.
void setOccurenceNumber (unsigned int n)
Set the occurence number of this occurence.
unsigned int updateOccurenceNumber (unsigned int n)
Update the occurence number of this occurence branch.
void setVisibility (bool visibility)
Set this occurence and children visibility.
void setRenderProperties (const GLC_RenderProperties &renderProperties)
set the renderProperties of this occurence
void removeEmptyChildren ()
Remove empty children.
void setReference (GLC_StructReference *pRef)
Set the given reference to this occurence.
void setAutomatic3DViewInstanceCreationUsage (bool usage)
Set the automatic creation of 3DViewInstance usage.
void makeFlexible (const GLC_Matrix4x4 &relativeMatrix)
Make this occurence a flexible occurence.
void makeRigid ()
Make this occurence rigid.
void swap (int i, int j)
Exchange the occurrence at index position i with the occurrence at index position j.
Private Member Functions
void detach ()
Detach the occurence from the GLC_World.
void doCreateOccurrenceFromInstance (GLuint shaderId)
Create occurrence from instance and given shader id.
Private Attributes
GLC_uint m_Uid
Occurence Unique ID.
GLC_WorldHandle * m_pWorldHandle
the occurence's World Handle
int * m_pNumberOfOccurence
Number of this Occurence.
GLC_StructInstance * m_pStructInstance
The struct instance of this occurence.
GLC_StructOccurence * m_pParent
The parent of this occurence.
QList< GLC_StructOccurence * > m_Childs
The Child of this occurence.
GLC_Matrix4x4 m_AbsoluteMatrix
The absolute matrix of the occurence.
unsigned int m_OccurenceNumber
The occurence number.
bool m_IsVisible
Flag to know if a occurence without instance is visible.
GLC_RenderProperties * m_pRenderProperties
The occurence rendering properties.
bool m_AutomaticCreationOf3DViewInstance
Automatique création of 3DViewInstance.
GLC_Matrix4x4 * m_pRelativeMatrix
The relative matrix of this occurence if this occurence is flexible.
Get Functions
GLC_uint id () const
Return this Occurence id.
const QString name () const
Return the instance name of this occurence.
GLC_Matrix4x4 absoluteMatrix () const
Return the absolute matrix of this occurence.
GLC_Matrix4x4 occurrenceRelativeMatrix () const
Return the surcharged relative matrix.
bool isOrphan () const
Return true if this occurence is orphan.
bool hasParent () const
Return true if this occurence has parent.
bool hasRepresentation () const
Return true if this occurence has a representation.
bool has3DViewInstance () const
Return true if this occurence has 3DViewInstance.
GLC_StructInstance * structInstance () const
Return the instance of this occurence.
GLC_StructReference * structReference () const
Return the reference of this occurence.
int childCount () const
Return the number of childs.
bool hasChild () const
Return true if the occurence has child.
bool canBeAddedToChildren (GLC_StructOccurence *pOccurence) const
Return true if the given occurence can be added to this occurence children.
GLC_StructOccurence * parent () const
Return The parent of this occurence.
GLC_StructOccurence * child (const int index) const
Return a child of this occurence.
QList< GLC_StructOccurence * > children () const
Return the list of children of this occurence.
QList< GLC_StructOccurence * > subOccurenceList () const
Return the list of all accurence under this occurence.
unsigned int numberOfFaces () const
Return the number of faces of the representation of this occurence.
unsigned int numberOfVertex () const
Return the number of vertex of the representation of this occurence.
unsigned int numberOfMaterials () const
Return the number of materials of the representation of this occurence.
QSet< GLC_Material * > materialSet () const
Return the materials List of the representation of this occurence.
GLC_StructOccurence * clone (GLC_WorldHandle *, bool shareInstance) const
Return a clone this occurence.
bool isVisible () const
Return true if this occurence is visible.
GLC_BoundingBox boundingBox () const
Return the occurence Bounding Box.
unsigned int occurenceNumber () const
Return the occurence number of this occurence.
GLC_RenderProperties * renderPropertiesHandle () const
Return an handle of the renderProperties of this occurence.
unsigned int nodeCount () const
Return the number of node of this branch.
GLC_WorldHandle * worldHandle () const
Return the world handle of this occurence.
QSet< GLC_StructReference * > childrenReferences () const
Return the Set of children references of this occurence.
bool useAutomatic3DViewInstanceCreation () const
Return true if the automatic creation of 3DViewInstance is used.
bool isFlexible () const
Return true if this occurence is flexible.
int indexOf (const GLC_StructOccurence *pOcc) const
Return the index position of the given occurrence.
bool containsChild (const GLC_StructOccurence *pOcc) const
Return true if this occurence contains the given occurence has child.
static QSet
< GLC_StructReference * > parentsReferences (const GLC_StructOccurence *pOccurence)
Return the set of parents references of the given occurence.
Detailed Description
GLC_StructOccurence : A scene graph occurence node.
Definition at line 43 of file glc_structoccurence.h.
Constructor & Destructor Documentation
GLC_StructOccurence::GLC_StructOccurence ()
Default constructor.
Definition at line 31 of file glc_structoccurence.cpp.
References m_pStructInstance, and GLC_StructInstance::structOccurenceCreated().
Referenced by addChild(), clone(), and insertChild().
GLC_StructOccurence::GLC_StructOccurence (GLC_StructInstance * pStructInstance, GLC_WorldHandle * pWorldHandle = NULL, GLuint shaderId = 0)
Create Occurence of the specified instance.
Definition at line 49 of file glc_structoccurence.cpp.
References doCreateOccurrenceFromInstance().
GLC_StructOccurence::GLC_StructOccurence (GLC_StructInstance * pStructInstance, GLC_uint id, GLC_WorldHandle * pWorldHandle = NULL, GLuint shaderId = 0)
Create Occurence of the specified instance and Uid.
Definition at line 66 of file glc_structoccurence.cpp.
References doCreateOccurrenceFromInstance().
GLC_StructOccurence::GLC_StructOccurence (GLC_3DRep * pRep)
Construct Occurence with the specified GLC_3DRep.
Definition at line 83 of file glc_structoccurence.cpp.
References m_pStructInstance, and GLC_StructInstance::structOccurenceCreated().
GLC_StructOccurence::GLC_StructOccurence (GLC_3DRep * pRep, GLC_uint id)
Construct Occurence from the given GLC_3DRep and Uid.
Definition at line 103 of file glc_structoccurence.cpp.
References m_pStructInstance, and GLC_StructInstance::structOccurenceCreated().
GLC_StructOccurence::GLC_StructOccurence (GLC_WorldHandle * pWorldHandle, const GLC_StructOccurence & structOccurence, bool shareInstance)
Copy constructor.
Definition at line 123 of file glc_structoccurence.cpp.
References addChild(), GLC_WorldHandle::addOccurence(), child(), childCount(), clone(), GLC_WorldHandle::collection(), GLC_3DViewCollection::contains(), has3DViewInstance(), id(), GLC_3DViewCollection::instanceHandle(), GLC_RenderProperties::isDefault(), GLC_3DViewCollection::isInAShadingGroup(), GLC_3DViewInstance::isSelected(), m_pNumberOfOccurence, m_pRelativeMatrix, m_pRenderProperties, m_pStructInstance, m_pWorldHandle, GLC_3DViewInstance::renderPropertiesHandle(), GLC_3DViewInstance::setRenderProperties(), GLC_3DViewCollection::shadingGroup(), GLC_StructInstance::structOccurenceCreated(), updateAbsoluteMatrix(), and updateChildrenAbsoluteMatrix().
GLC_StructOccurence::~GLC_StructOccurence () virtual
Destructor.
Definition at line 208 of file glc_structoccurence.cpp.
References GLC_ErrorLog::addError(), GLC_StructInstance::hasStructOccurence(), m_Childs, m_pNumberOfOccurence, m_pRelativeMatrix, m_pRenderProperties, m_pStructInstance, m_pWorldHandle, GLC_StructReference::name(), removeChild(), GLC_WorldHandle::removeOccurence(), GLC_StructInstance::structOccurenceDeleted(), and GLC_StructInstance::structReference().
Member Function Documentation
GLC_Matrix4x4 GLC_StructOccurence::absoluteMatrix () const inline
Return the absolute matrix of this occurence.
Definition at line 86 of file glc_structoccurence.h.
Referenced by GLC_WorldTo3ds::createNodeFromOccurrence(), and updateAbsoluteMatrix().
void GLC_StructOccurence::addChild (GLC_StructOccurence * pChild)
Add Child.
The new child must be orphan
Definition at line 559 of file glc_structoccurence.cpp.
References isOrphan(), m_Childs, m_pParent, m_pWorldHandle, setWorldHandle(), and updateChildrenAbsoluteMatrix().
Referenced by GLC_StructReference::addChild(), addChild(), GLC_ObjToWorld::addCurrentObjMeshToWorld(), GLC_3dsToWorld::createMeshes(), GLC_ColladaToWorld::createOccurenceFromNode(), GLC_ColladaToWorld::createSceneGraph(), GLC_3dxmlToWorld::createUnfoldedTree(), GLC_OffToWorld::CreateWorldFromOff(), GLC_StlToWorld::CreateWorldFromStl(), doCreateOccurrenceFromInstance(), GLC_StructOccurence(), GLC_World::mergeWithAnotherWorld(), GLC_StlToWorld::scanFacet(), and setReference().
GLC_StructOccurence * GLC_StructOccurence::addChild (GLC_StructInstance * pInstance)
Add Child instance and returns the newly created occurence.
Definition at line 594 of file glc_structoccurence.cpp.
References addChild(), GLC_StructOccurence(), and m_pWorldHandle.
GLC_BoundingBox GLC_StructOccurence::boundingBox (void) const
Return the occurence Bounding Box.
Definition at line 421 of file glc_structoccurence.cpp.
References GLC_3DViewInstance::boundingBox(), children(), GLC_WorldHandle::collection(), GLC_BoundingBox::combine(), GLC_3DViewCollection::contains(), has3DViewInstance(), hasChild(), GLC_3DViewCollection::instanceHandle(), and m_pWorldHandle.
bool GLC_StructOccurence::canBeAddedToChildren (GLC_StructOccurence * pOccurence) const
Return true if the given occurence can be added to this occurence children.
Definition at line 284 of file glc_structoccurence.cpp.
References childrenReferences(), GLC_StructInstance::hasStructOccurence(), m_pStructInstance, parentsReferences(), and structReference().
GLC_StructOccurence* GLC_StructOccurence::child (const int index) const inline
Return a child of this occurence.
The index must exist
Definition at line 134 of file glc_structoccurence.h.
Referenced by GLC_3dxmlToWorld::applyV4Attribute(), GLC_WorldTo3dxml::exportAssemblyFromOccurence(), GLC_StructOccurence(), isVisible(), GLC_WorldTo3ds::saveBranch(), and GLC_WorldTo3ds::saveWorld().
int GLC_StructOccurence::childCount () const inline
Return the number of childs.
Definition at line 118 of file glc_structoccurence.h.
Referenced by GLC_3dxmlToWorld::applyV4Attribute(), childrenReferences(), GLC_ObjToWorld::CreateWorldFromObj(), GLC_WorldTo3dxml::exportAssemblyFromOccurence(), GLC_StructOccurence(), indexOf(), isVisible(), GLC_World::mergeWithAnotherWorld(), GLC_WorldTo3ds::saveBranch(), GLC_WorldTo3ds::saveWorld(), setRenderProperties(), setVisibility(), subOccurenceList(), and updateOccurenceNumber().
QList<GLC_StructOccurence*> GLC_StructOccurence::children () const inline
Return the list of children of this occurence.
Definition at line 138 of file glc_structoccurence.h.
Referenced by boundingBox(), and GLC_World::mergeWithAnotherWorld().
QSet< GLC_StructReference * > GLC_StructOccurence::childrenReferences () const
Return the Set of children references of this occurence.
Definition at line 461 of file glc_structoccurence.cpp.
References childCount(), m_Childs, structInstance(), and structReference().
Referenced by canBeAddedToChildren().
GLC_StructOccurence * GLC_StructOccurence::clone (GLC_WorldHandle * pWorldHandle, bool shareInstance) const
Return a clone this occurence.
Definition at line 391 of file glc_structoccurence.cpp.
References GLC_StructOccurence().
Referenced by doCreateOccurrenceFromInstance(), GLC_StructOccurence(), GLC_World::mergeWithAnotherWorld(), and setReference().
bool GLC_StructOccurence::containsChild (const GLC_StructOccurence * pOcc) const
Return true if this occurence contains the given occurence has child.
Definition at line 511 of file glc_structoccurence.cpp.
References parent().
bool GLC_StructOccurence::create3DViewInstance (GLuint shaderId = 0)
Create the 3DViewInstance of this occurence if there is a valid 3DRep.
Definition at line 645 of file glc_structoccurence.cpp.
References GLC_3DViewCollection::add(), GLC_3DViewCollection::bindShader(), GLC_WorldHandle::collection(), GLC_SelectionSet::contains(), has3DViewInstance(), hasRepresentation(), m_IsVisible, m_pRenderProperties, m_pWorldHandle, m_Uid, name(), GLC_StructReference::representationHandle(), GLC_3DViewCollection::select(), GLC_WorldHandle::selectionSetHandle(), GLC_Object::setName(), GLC_3DViewInstance::setRenderProperties(), GLC_3DViewCollection::setVisibility(), and structReference().
Referenced by GLC_WorldHandle::addOccurence(), GLC_StructReference::loadRepresentation(), loadRepresentation(), and GLC_StructReference::setRepresentation().
void GLC_StructOccurence::detach () private
Detach the occurence from the GLC_World.
Definition at line 910 of file glc_structoccurence.cpp.
References GLC_WorldHandle::collection(), GLC_3DViewCollection::contains(), GLC_3DViewCollection::instanceHandle(), GLC_RenderProperties::isDefault(), m_Childs, m_pRenderProperties, m_pWorldHandle, m_Uid, GLC_WorldHandle::removeOccurence(), and GLC_3DViewInstance::renderPropertiesHandle().
Referenced by makeOrphan(), and removeChild().
void GLC_StructOccurence::doCreateOccurrenceFromInstance (GLuint shaderId) private
Create occurrence from instance and given shader id.
Definition at line 937 of file glc_structoccurence.cpp.
References addChild(), GLC_WorldHandle::addOccurence(), clone(), GLC_StructInstance::firstOccurenceHandle(), GLC_StructInstance::hasStructOccurence(), m_Childs, m_pNumberOfOccurence, m_pStructInstance, m_pWorldHandle, GLC_StructInstance::structOccurenceCreated(), and updateAbsoluteMatrix().
Referenced by GLC_StructOccurence().
bool GLC_StructOccurence::has3DViewInstance () const
Return true if this occurence has 3DViewInstance.
Definition at line 275 of file glc_structoccurence.cpp.
References GLC_WorldHandle::collection(), GLC_3DViewCollection::contains(), m_pWorldHandle, and m_Uid.
Referenced by boundingBox(), create3DViewInstance(), GLC_StructOccurence(), GLC_StructReference::loadRepresentation(), loadRepresentation(), reverseNormals(), setRenderProperties(), GLC_StructReference::setRepresentation(), setVisibility(), and unloadRepresentation().
bool GLC_StructOccurence::hasChild () const inline
Return true if the occurence has child.
Definition at line 122 of file glc_structoccurence.h.
Referenced by GLC_3dxmlToWorld::applyV4Attribute(), boundingBox(), GLC_WorldHandle::select(), setRenderProperties(), subOccurenceList(), and GLC_WorldHandle::unselect().
bool GLC_StructOccurence::hasParent () const inline
Return true if this occurence has parent.
Definition at line 97 of file glc_structoccurence.h.
bool GLC_StructOccurence::hasRepresentation () const
Return true if this occurence has a representation.
Definition at line 266 of file glc_structoccurence.cpp.
References GLC_StructReference::hasRepresentation(), m_pStructInstance, GLC_StructInstance::structReference(), and structReference().
Referenced by create3DViewInstance(), loadRepresentation(), materialSet(), numberOfFaces(), numberOfMaterials(), numberOfVertex(), and unloadRepresentation().
GLC_uint GLC_StructOccurence::id () const inline
Return this Occurence id.
Definition at line 78 of file glc_structoccurence.h.
Referenced by GLC_WorldHandle::addOccurence(), GLC_SelectionSet::contains(), GLC_WorldTo3ds::createNodeFromOccurrence(), GLC_WorldTo3dxml::exportAssemblyFromOccurence(), GLC_StructOccurence(), GLC_SelectionSet::insert(), GLC_SelectionSet::remove(), GLC_WorldHandle::removeOccurence(), GLC_World::select(), and GLC_WorldTo3dxml::writeOccurenceDefaultViewProperty().
int GLC_StructOccurence::indexOf (const GLC_StructOccurence * pOcc) const
Return the index position of the given occurrence.
Return -1 if the given occurence is not a child of this occurence
Definition at line 493 of file glc_structoccurence.cpp.
References childCount(), and m_Childs.
void GLC_StructOccurence::insertChild (int index, GLC_StructOccurence * pChild)
insert Child at the given position
The new child must be orphan and index >= childcount
Definition at line 576 of file glc_structoccurence.cpp.
References isOrphan(), m_Childs, m_pParent, m_pWorldHandle, setWorldHandle(), and updateChildrenAbsoluteMatrix().
Referenced by insertChild().
GLC_StructOccurence * GLC_StructOccurence::insertChild (int index, GLC_StructInstance * pInstance)
Insert Child instance and returns the newly created occurence.
Definition at line 604 of file glc_structoccurence.cpp.
References GLC_StructOccurence(), insertChild(), and m_pWorldHandle.
bool GLC_StructOccurence::isFlexible () const inline
Return true if this occurence is flexible.
Definition at line 191 of file glc_structoccurence.h.
Referenced by GLC_WorldTo3dxml::exportAssemblyFromOccurence(), and GLC_WorldTo3dxml::writeOccurenceDefaultViewProperty().
bool GLC_StructOccurence::isOrphan () const inline
Return true if this occurence is orphan.
Definition at line 93 of file glc_structoccurence.h.
Referenced by addChild(), GLC_3dxmlToWorld::createUnfoldedTree(), GLC_WorldTo3dxml::exportAssemblyFromOccurence(), insertChild(), GLC_WorldTo3dxml::instancePath(), GLC_3dxmlToWorld::loadProductStructure(), makeOrphan(), and GLC_World::replaceRootOccurrence().
bool GLC_StructOccurence::isVisible () const
Return true if this occurence is visible.
Definition at line 396 of file glc_structoccurence.cpp.
References child(), childCount(), GLC_WorldHandle::collection(), GLC_3DViewCollection::contains(), GLC_3DViewCollection::instanceHandle(), GLC_3DViewInstance::isVisible(), isVisible(), m_IsVisible, m_pWorldHandle, and m_Uid.
Referenced by isVisible(), and GLC_WorldTo3dxml::writeOccurenceDefaultViewProperty().
bool GLC_StructOccurence::loadRepresentation ()
Load the representation and return true if success.
Definition at line 711 of file glc_structoccurence.cpp.
References create3DViewInstance(), has3DViewInstance(), hasRepresentation(), GLC_StructReference::loadRepresentation(), m_AutomaticCreationOf3DViewInstance, m_pStructInstance, GLC_StructReference::representationIsLoaded(), GLC_StructInstance::structReference(), and structReference().
void GLC_StructOccurence::makeFlexible (const GLC_Matrix4x4 & relativeMatrix)
Make this occurence a flexible occurence.
Definition at line 873 of file glc_structoccurence.cpp.
References m_pRelativeMatrix, and updateChildrenAbsoluteMatrix().
Referenced by GLC_3dxmlToWorld::applyV4Attribute().
void GLC_StructOccurence::makeOrphan ()
make the occurence orphan
Definition at line 614 of file glc_structoccurence.cpp.
References detach(), isOrphan(), m_pParent, and removeChild().
Referenced by GLC_World::takeRootOccurrence().
void GLC_StructOccurence::makeRigid ()
Make this occurence rigid.
Definition at line 881 of file glc_structoccurence.cpp.
References m_pRelativeMatrix, and updateChildrenAbsoluteMatrix().
QSet< GLC_Material * > GLC_StructOccurence::materialSet () const
Return the materials List of the representation of this occurence.
Definition at line 374 of file glc_structoccurence.cpp.
References hasRepresentation(), m_Childs, GLC_StructReference::materialSet(), structInstance(), and GLC_StructInstance::structReference().
Referenced by numberOfMaterials().
const QString GLC_StructOccurence::name () const inline
Return the instance name of this occurence.
Definition at line 82 of file glc_structoccurence.h.
Referenced by create3DViewInstance(), GLC_3dxmlToWorld::createUnfoldedTree(), and GLC_3dxmlToWorld::loadProductStructure().
unsigned int GLC_StructOccurence::nodeCount () const
Return the number of node of this branch.
Definition at line 450 of file glc_structoccurence.cpp.
References m_Childs.
unsigned int GLC_StructOccurence::numberOfFaces () const
Return the number of faces of the representation of this occurence.
Definition at line 322 of file glc_structoccurence.cpp.
References hasRepresentation(), m_Childs, GLC_StructReference::numberOfFaces(), structInstance(), and GLC_StructInstance::structReference().
unsigned int GLC_StructOccurence::numberOfMaterials () const
Return the number of materials of the representation of this occurence.
Definition at line 355 of file glc_structoccurence.cpp.
References hasRepresentation(), m_Childs, materialSet(), GLC_StructReference::numberOfMaterials(), structInstance(), and GLC_StructInstance::structReference().
unsigned int GLC_StructOccurence::numberOfVertex () const
Return the number of vertex of the representation of this occurence.
Definition at line 339 of file glc_structoccurence.cpp.
References hasRepresentation(), m_Childs, GLC_StructReference::numberOfVertex(), structInstance(), and GLC_StructInstance::structReference().
unsigned int GLC_StructOccurence::occurenceNumber () const inline
Return the occurence number of this occurence.
Definition at line 166 of file glc_structoccurence.h.
GLC_Matrix4x4 GLC_StructOccurence::occurrenceRelativeMatrix () const
Return the surcharged relative matrix.
Definition at line 256 of file glc_structoccurence.cpp.
References m_pRelativeMatrix.
Referenced by GLC_WorldTo3dxml::writeOccurenceDefaultViewProperty().
GLC_StructOccurence* GLC_StructOccurence::parent () const inline
Return The parent of this occurence.
Definition at line 129 of file glc_structoccurence.h.
Referenced by containsChild(), GLC_WorldTo3ds::createNodeFromOccurrence(), GLC_WorldTo3dxml::exportAssemblyFromOccurence(), GLC_WorldTo3dxml::instancePath(), and parentsReferences().
QSet< GLC_StructReference * > GLC_StructOccurence::parentsReferences (const GLC_StructOccurence * pOccurence) static
Return the set of parents references of the given occurence.
Definition at line 477 of file glc_structoccurence.cpp.
References parent(), structInstance(), and structReference().
Referenced by canBeAddedToChildren().
bool GLC_StructOccurence::remove3DViewInstance ()
Remove the 3DViewInstance of this occurence.
Definition at line 675 of file glc_structoccurence.cpp.
References GLC_WorldHandle::collection(), m_pWorldHandle, m_Uid, and GLC_3DViewCollection::remove().
bool GLC_StructOccurence::removeChild (GLC_StructOccurence * pChild)
Remove the specified child.
The removed child will not be deleted
Definition at line 626 of file glc_structoccurence.cpp.
References detach(), m_Childs, and m_pParent.
Referenced by makeOrphan(), and ~GLC_StructOccurence().
void GLC_StructOccurence::removeEmptyChildren ()
Remove empty children.
Definition at line 815 of file glc_structoccurence.cpp.
References m_Childs.
Referenced by GLC_ColladaToWorld::createSceneGraph().
GLC_RenderProperties* GLC_StructOccurence::renderPropertiesHandle () const inline
Return an handle of the renderProperties of this occurence.
Definition at line 170 of file glc_structoccurence.h.
void GLC_StructOccurence::reverseNormals ()
Reverse Normals of this Occurence and childs.
Definition at line 637 of file glc_structoccurence.cpp.
References GLC_WorldHandle::collection(), has3DViewInstance(), GLC_3DViewCollection::instanceHandle(), m_pWorldHandle, and GLC_3DViewInstance::reverseGeometriesNormals().
void GLC_StructOccurence::setAutomatic3DViewInstanceCreationUsage (bool usage) inline
Set the automatic creation of 3DViewInstance usage.
Definition at line 275 of file glc_structoccurence.h.
void GLC_StructOccurence::setName (const QString name) inline
Set Occurence instance Name.
Definition at line 208 of file glc_structoccurence.h.
Referenced by GLC_3dsToWorld::createMeshes().
void GLC_StructOccurence::setOccurenceNumber (unsigned int n) inline
Set the occurence number of this occurence.
Definition at line 256 of file glc_structoccurence.h.
void GLC_StructOccurence::setReference (GLC_StructReference * pRef)
Set the given reference to this occurence.
Definition at line 833 of file glc_structoccurence.cpp.
References addChild(), clone(), GLC_StructReference::firstInstanceHandle(), GLC_StructInstance::firstOccurenceHandle(), GLC_StructReference::hasStructInstance(), GLC_StructInstance::hasStructOccurence(), GLC_StructReference::listOfStructInstances(), m_Childs, m_pNumberOfOccurence, m_pStructInstance, m_pWorldHandle, GLC_StructInstance::setReference(), and GLC_StructInstance::structReference().
void GLC_StructOccurence::setRenderProperties (const GLC_RenderProperties & renderProperties)
set the renderProperties of this occurence
Definition at line 791 of file glc_structoccurence.cpp.
References childCount(), GLC_WorldHandle::collection(), has3DViewInstance(), hasChild(), GLC_3DViewCollection::instanceHandle(), m_Childs, m_pRenderProperties, m_pWorldHandle, m_Uid, and GLC_3DViewInstance::setRenderProperties().
Referenced by GLC_3dxmlToWorld::applyV4Attribute().
void GLC_StructOccurence::setVisibility (bool visibility)
Set this occurence and children visibility.
Definition at line 777 of file glc_structoccurence.cpp.
References childCount(), GLC_WorldHandle::collection(), has3DViewInstance(), m_Childs, m_IsVisible, m_pWorldHandle, m_Uid, and GLC_3DViewCollection::setVisibility().
Referenced by GLC_3dxmlToWorld::applyV4Attribute().
void GLC_StructOccurence::setWorldHandle (GLC_WorldHandle * pWorldHandle)
Set this occurence world Handle.
Definition at line 685 of file glc_structoccurence.cpp.
References GLC_WorldHandle::addOccurence(), GLC_WorldHandle::collection(), m_Childs, m_IsVisible, m_pWorldHandle, m_Uid, GLC_WorldHandle::removeOccurence(), and GLC_3DViewCollection::setVisibility().
Referenced by addChild(), GLC_World::GLC_World(), insertChild(), GLC_World::replaceRootOccurrence(), and GLC_World::takeRootOccurrence().
GLC_StructInstance* GLC_StructOccurence::structInstance () const inline
Return the instance of this occurence.
Definition at line 107 of file glc_structoccurence.h.
Referenced by GLC_StructReference::addChild(), GLC_3dxmlToWorld::applyV4Attribute(), childrenReferences(), GLC_WorldTo3ds::createNodeFromOccurrence(), GLC_WorldTo3dxml::exportAssemblyFromOccurence(), GLC_WorldTo3dxml::instancePath(), GLC_3dxmlToWorld::loadReference3D(), materialSet(), numberOfFaces(), numberOfMaterials(), numberOfVertex(), and parentsReferences().
GLC_StructReference* GLC_StructOccurence::structReference () const inline
Return the reference of this occurence.
Definition at line 111 of file glc_structoccurence.h.
Referenced by GLC_WorldHandle::addOccurence(), canBeAddedToChildren(), childrenReferences(), create3DViewInstance(), GLC_WorldTo3ds::createNodeFromOccurrence(), GLC_WorldTo3dxml::exportAssemblyFromOccurence(), hasRepresentation(), loadRepresentation(), parentsReferences(), swap(), and unloadRepresentation().
QList< GLC_StructOccurence * > GLC_StructOccurence::subOccurenceList () const
Return the list of all accurence under this occurence.
Definition at line 305 of file glc_structoccurence.cpp.
References childCount(), hasChild(), m_Childs, and subOccurenceList().
Referenced by GLC_WorldHandle::select(), subOccurenceList(), and GLC_WorldHandle::unselect().
void GLC_StructOccurence::swap (int i, int j)
Exchange the occurrence at index position i with the occurrence at index position j.
This function assumes that both i and j are at least 0 but less than childCount().
Definition at line 889 of file glc_structoccurence.cpp.
References GLC_StructReference::listOfStructOccurence(), m_Childs, and structReference().
bool GLC_StructOccurence::unloadRepresentation ()
UnLoad the representation and return true if success.
Definition at line 737 of file glc_structoccurence.cpp.
References GLC_WorldHandle::collection(), has3DViewInstance(), hasRepresentation(), m_pWorldHandle, m_Uid, GLC_3DViewCollection::remove(), GLC_StructReference::representationIsLoaded(), GLC_StructReference::setOfStructOccurence(), structReference(), and GLC_StructReference::unloadRepresentation().
GLC_StructOccurence * GLC_StructOccurence::updateAbsoluteMatrix ()
Update the absolute matrix.
Definition at line 519 of file glc_structoccurence.cpp.
References absoluteMatrix(), GLC_WorldHandle::collection(), GLC_3DViewCollection::contains(), GLC_3DViewCollection::instanceHandle(), m_AbsoluteMatrix, m_pParent, m_pRelativeMatrix, m_pStructInstance, m_pWorldHandle, m_Uid, GLC_StructInstance::relativeMatrix(), and GLC_3DViewInstance::setMatrix().
Referenced by doCreateOccurrenceFromInstance(), GLC_StructOccurence(), and updateChildrenAbsoluteMatrix().
GLC_StructOccurence * GLC_StructOccurence::updateChildrenAbsoluteMatrix ()
Update children obsolute Matrix.
Definition at line 548 of file glc_structoccurence.cpp.
References m_Childs, and updateAbsoluteMatrix().
Referenced by addChild(), GLC_ColladaToWorld::createSceneGraph(), GLC_3dxmlToWorld::createUnfoldedTree(), GLC_StructOccurence(), insertChild(), makeFlexible(), makeRigid(), and GLC_World::mergeWithAnotherWorld().
unsigned int GLC_StructOccurence::updateOccurenceNumber (unsigned int n)
Update the occurence number of this occurence branch.
Definition at line 766 of file glc_structoccurence.cpp.
References childCount(), m_Childs, and m_OccurenceNumber.
Referenced by GLC_WorldTo3dxml::GLC_WorldTo3dxml(), and GLC_3dxmlToWorld::loadProductStructure().
bool GLC_StructOccurence::useAutomatic3DViewInstanceCreation () const inline
Return true if the automatic creation of 3DViewInstance is used.
Definition at line 187 of file glc_structoccurence.h.
Referenced by GLC_WorldHandle::addOccurence(), GLC_StructReference::loadRepresentation(), and GLC_StructReference::setRepresentation().
GLC_WorldHandle* GLC_StructOccurence::worldHandle () const inline
Return the world handle of this occurence.
Definition at line 177 of file glc_structoccurence.h.
Member Data Documentation
GLC_Matrix4x4 GLC_StructOccurence::m_AbsoluteMatrix private
The absolute matrix of the occurence.
Definition at line 322 of file glc_structoccurence.h.
Referenced by updateAbsoluteMatrix().
bool GLC_StructOccurence::m_AutomaticCreationOf3DViewInstance private
Automatique création of 3DViewInstance.
Definition at line 334 of file glc_structoccurence.h.
Referenced by loadRepresentation().
QList<GLC_StructOccurence*> GLC_StructOccurence::m_Childs private
The Child of this occurence.
Definition at line 319 of file glc_structoccurence.h.
Referenced by addChild(), childrenReferences(), detach(), doCreateOccurrenceFromInstance(), indexOf(), insertChild(), materialSet(), nodeCount(), numberOfFaces(), numberOfMaterials(), numberOfVertex(), removeChild(), removeEmptyChildren(), setReference(), setRenderProperties(), setVisibility(), setWorldHandle(), subOccurenceList(), swap(), updateChildrenAbsoluteMatrix(), updateOccurenceNumber(), and ~GLC_StructOccurence().
bool GLC_StructOccurence::m_IsVisible private
Flag to know if a occurence without instance is visible.
Definition at line 328 of file glc_structoccurence.h.
Referenced by create3DViewInstance(), isVisible(), setVisibility(), and setWorldHandle().
unsigned int GLC_StructOccurence::m_OccurenceNumber private
The occurence number.
Definition at line 325 of file glc_structoccurence.h.
Referenced by updateOccurenceNumber().
int* GLC_StructOccurence::m_pNumberOfOccurence private
Number of this Occurence.
Definition at line 310 of file glc_structoccurence.h.
Referenced by doCreateOccurrenceFromInstance(), GLC_StructOccurence(), setReference(), and ~GLC_StructOccurence().
GLC_StructOccurence* GLC_StructOccurence::m_pParent private
The parent of this occurence.
Definition at line 316 of file glc_structoccurence.h.
Referenced by addChild(), insertChild(), makeOrphan(), removeChild(), and updateAbsoluteMatrix().
GLC_Matrix4x4* GLC_StructOccurence::m_pRelativeMatrix private
The relative matrix of this occurence if this occurence is flexible.
Definition at line 337 of file glc_structoccurence.h.
Referenced by GLC_StructOccurence(), makeFlexible(), makeRigid(), occurrenceRelativeMatrix(), updateAbsoluteMatrix(), and ~GLC_StructOccurence().
GLC_RenderProperties* GLC_StructOccurence::m_pRenderProperties private
The occurence rendering properties.
Definition at line 331 of file glc_structoccurence.h.
Referenced by create3DViewInstance(), detach(), GLC_StructOccurence(), setRenderProperties(), and ~GLC_StructOccurence().
GLC_StructInstance* GLC_StructOccurence::m_pStructInstance private
The struct instance of this occurence.
Definition at line 313 of file glc_structoccurence.h.
Referenced by canBeAddedToChildren(), doCreateOccurrenceFromInstance(), GLC_StructOccurence(), hasRepresentation(), loadRepresentation(), setReference(), updateAbsoluteMatrix(), and ~GLC_StructOccurence().
GLC_WorldHandle* GLC_StructOccurence::m_pWorldHandle private
the occurence's World Handle
Definition at line 307 of file glc_structoccurence.h.
Referenced by addChild(), boundingBox(), create3DViewInstance(), detach(), doCreateOccurrenceFromInstance(), GLC_StructOccurence(), has3DViewInstance(), insertChild(), isVisible(), remove3DViewInstance(), reverseNormals(), setReference(), setRenderProperties(), setVisibility(), setWorldHandle(), unloadRepresentation(), updateAbsoluteMatrix(), and ~GLC_StructOccurence().
GLC_uint GLC_StructOccurence::m_Uid private
Occurence Unique ID.
Definition at line 304 of file glc_structoccurence.h.
Referenced by create3DViewInstance(), detach(), has3DViewInstance(), isVisible(), remove3DViewInstance(), setRenderProperties(), setVisibility(), setWorldHandle(), unloadRepresentation(), and updateAbsoluteMatrix().
The documentation for this class was generated from the following files:
glc_structoccurence.h
glc_structoccurence.cpp
©2005-2013 Laurent Ribon