GLC_lib: GLC_Vector3df Class Reference
GLC_Vector3df Class Reference
GLC_Vector3df is a 3 dimensions Vector.
#include <glc_vector3df.h>
Public Member Functions
Constructor / Destructor
GLC_Vector3df ()
GLC_Vector3df (const float &dX, const float &dY, const float &dZ)
Standard constructor With x, y, z.
GLC_Vector3df (const GLC_Vector3df &Vect)
Set Functions
GLC_Vector3df & setX (const float &dX)
X Compound.
GLC_Vector3df & setY (const float &dY)
Y Compound.
GLC_Vector3df & setZ (const float &dZ)
Z Compound.
GLC_Vector3df & setVect (const float &dX, const float &dY, const float &dZ)
All Compound.
GLC_Vector3df & setVect (const GLC_Vector3df &Vect)
From another Vector.
GLC_Vector3df & setInv (void)
Invert Vector.
Get Functions
float x (void) const
Return X Compound.
float y (void) const
Return Y Compound.
float z (void) const
Return Z Compound.
const float * data (void) const
Return a pointer to vector data.
bool isNull (void) const
Return true if the vector is null.
Private Attributes
float m_Vector [3]
Friends
class GLC_Vector4d
class GLC_Vector3d
Detailed Description
GLC_Vector3df is a 3 dimensions Vector.
GLC_Vector3df is used to represent 3D position and vectors.
Definition at line 39 of file glc_vector3df.h.
Constructor & Destructor Documentation
GLC_Vector3df::GLC_Vector3df () inline
Default constructor Value is set to
X = 0.0
Y = 0.0
Z = 0.0
Definition at line 54 of file glc_vector3df.h.
References GLC_Vector3d::m_Vector.
GLC_Vector3df::GLC_Vector3df (const float & dX, const float & dY, const float & dZ) inline
Standard constructor With x, y, z.
Definition at line 62 of file glc_vector3df.h.
References GLC_Vector3d::setVect().
GLC_Vector3df::GLC_Vector3df (const GLC_Vector3df & Vect) inline
Copy constructor Sample use
NewVect = new GLC_Vector3d(OldVect);
Definition at line 73 of file glc_vector3df.h.
References m_Vector, and GLC_Vector3d::m_Vector.
Member Function Documentation
const float* GLC_Vector3df::data (void) const inline
Return a pointer to vector data.
Definition at line 159 of file glc_vector3df.h.
References GLC_Vector3d::m_Vector.
bool GLC_Vector3df::isNull (void) const inline
Return true if the vector is null.
Definition at line 164 of file glc_vector3df.h.
References GLC_Vector3d::m_Vector.
GLC_Vector3df& GLC_Vector3df::setInv (void) inline
Invert Vector.
Definition at line 128 of file glc_vector3df.h.
References GLC_Vector3d::m_Vector.
GLC_Vector3df& GLC_Vector3df::setVect (const float & dX, const float & dY, const float & dZ) inline
All Compound.
Definition at line 109 of file glc_vector3df.h.
References GLC_Vector3d::m_Vector.
Referenced by GLC_StlToWorld::extract3dVect().
GLC_Vector3df& GLC_Vector3df::setVect (const GLC_Vector3df & Vect) inline
From another Vector.
Definition at line 119 of file glc_vector3df.h.
References m_Vector, and GLC_Vector3d::m_Vector.
GLC_Vector3df& GLC_Vector3df::setX (const float & dX) inline
X Compound.
Definition at line 88 of file glc_vector3df.h.
References GLC_Vector3d::m_Vector.
GLC_Vector3df& GLC_Vector3df::setY (const float & dY) inline
Y Compound.
Definition at line 95 of file glc_vector3df.h.
References GLC_Vector3d::m_Vector.
GLC_Vector3df& GLC_Vector3df::setZ (const float & dZ) inline
Z Compound.
Definition at line 102 of file glc_vector3df.h.
References GLC_Vector3d::m_Vector.
float GLC_Vector3df::x (void) const inline
Return X Compound.
Definition at line 144 of file glc_vector3df.h.
References GLC_Vector3d::m_Vector.
Referenced by GLC_PointCloud::addPoint(), GLC_Polylines::addPolyline(), GLC_OffToWorld::computeNormal(), GLC_ColladaToWorld::computeNormalOfCurrentPrimitiveOfCurrentMesh(), GLC_ObjToWorld::extractFaceIndex(), and GLC_StlToWorld::scanFacet().
float GLC_Vector3df::y (void) const inline
Return Y Compound.
Definition at line 149 of file glc_vector3df.h.
References GLC_Vector3d::m_Vector.
Referenced by GLC_OffToWorld::computeNormal(), GLC_ColladaToWorld::computeNormalOfCurrentPrimitiveOfCurrentMesh(), GLC_ObjToWorld::extractFaceIndex(), and GLC_StlToWorld::scanFacet().
float GLC_Vector3df::z (void) const inline
Return Z Compound.
Definition at line 154 of file glc_vector3df.h.
References GLC_Vector3d::m_Vector.
Referenced by GLC_OffToWorld::computeNormal(), GLC_ColladaToWorld::computeNormalOfCurrentPrimitiveOfCurrentMesh(), GLC_ObjToWorld::extractFaceIndex(), and GLC_StlToWorld::scanFacet().
Friends And Related Function Documentation
friend class GLC_Vector3d friend
Definition at line 42 of file glc_vector3df.h.
friend class GLC_Vector4d friend
Definition at line 41 of file glc_vector3df.h.
Member Data Documentation
float GLC_Vector3df::m_Vector[3] private
Vector array definition
data[0] X
data[1] Y
data[2] Z
Definition at line 181 of file glc_vector3df.h.
Referenced by GLC_Vector3d::GLC_Vector3d(), GLC_Vector3df(), GLC_Vector4d::GLC_Vector4d(), GLC_Vector3d::operator=(), GLC_Vector4d::operator=(), and setVect().
The documentation for this class was generated from the following file:
glc_vector3df.h
©2005-2013 Laurent Ribon