GLC_lib: GLC_Interpolator Class Reference
GLC_Interpolator Class Reference
GLC_Interpolator : Matrix interpolation class.
#include <glc_interpolator.h>
Public Member Functions
GLC_Interpolator ()
Default linear interpolation constructor.
void SetInterpolMat (int NbrPas, const GLC_Vector3d &VectDepart, const GLC_Vector3d &VectArrive, INTERPOL_TYPE Interpolation=INTERPOL_LINEAIRE)
Set interpolation matrix.
void SetType (INTERPOL_TYPE Interpolation)
Set interpolation type.
void SetNbrPas (int NbrPas)
void SetVecteurs (const GLC_Vector3d &VectDepart, const GLC_Vector3d &VectArrive)
Set start and end vector.
GLC_Matrix4x4 GetInterpolMat (void) const
Return th interpolation matrix.
Private Member Functions
bool CalcInterpolMat (void)
Compute interpolation matrix.
bool CalcInterpolLineaireMat (void)
Compute linear interolation matrix.
bool CalcInterpolAngulaireMat (void)
Compute angular interpolation matrix.
Private Attributes
GLC_Point3d m_StartPoint
Start Point.
GLC_Point3d m_EndPoint
End Point.
INTERPOL_TYPE m_InterpolType
Interpolation type.
int m_StepCount
Interpolation step count.
GLC_Matrix4x4 m_InterpolMat
Interpolation matrix.
Detailed Description
GLC_Interpolator : Matrix interpolation class.
An GLC_Interpolator is a class used to interpolate 2 4D matrix
Definition at line 47 of file glc_interpolator.h.
Constructor & Destructor Documentation
GLC_Interpolator::GLC_Interpolator ()
Default linear interpolation constructor.
Definition at line 29 of file glc_interpolator.cpp.
Member Function Documentation
bool GLC_Interpolator::CalcInterpolAngulaireMat (void) private
Compute angular interpolation matrix.
Definition at line 131 of file glc_interpolator.cpp.
References m_EndPoint, m_InterpolMat, m_StartPoint, m_StepCount, GLC_Matrix4x4::setMatRot(), and GLC_Matrix4x4::setToIdentity().
Referenced by CalcInterpolMat().
bool GLC_Interpolator::CalcInterpolLineaireMat (void) private
Compute linear interolation matrix.
Definition at line 115 of file glc_interpolator.cpp.
References GLC_Vector3d::isNull(), m_EndPoint, m_InterpolMat, m_StartPoint, m_StepCount, GLC_Matrix4x4::setMatTranslate(), and GLC_Matrix4x4::setToIdentity().
Referenced by CalcInterpolMat().
bool GLC_Interpolator::CalcInterpolMat (void) private
Compute interpolation matrix.
Definition at line 87 of file glc_interpolator.cpp.
References CalcInterpolAngulaireMat(), CalcInterpolLineaireMat(), INTERPOL_ANGULAIRE, INTERPOL_HOMOTETIE, INTERPOL_LINEAIRE, m_EndPoint, m_InterpolType, and m_StartPoint.
Referenced by SetInterpolMat(), SetNbrPas(), SetType(), and SetVecteurs().
GLC_Matrix4x4 GLC_Interpolator::GetInterpolMat (void) const inline
Return th interpolation matrix.
Definition at line 76 of file glc_interpolator.h.
void GLC_Interpolator::SetInterpolMat (int NbrPas, const GLC_Vector3d & VectDepart, const GLC_Vector3d & VectArrive, INTERPOL_TYPE Interpolation = INTERPOL_LINEAIRE)
Set interpolation matrix.
Definition at line 39 of file glc_interpolator.cpp.
References CalcInterpolMat(), m_EndPoint, m_InterpolType, m_StartPoint, and m_StepCount.
void GLC_Interpolator::SetNbrPas (int NbrPas)
Definition at line 62 of file glc_interpolator.cpp.
References CalcInterpolMat(), and m_StepCount.
void GLC_Interpolator::SetType (INTERPOL_TYPE Interpolation)
Set interpolation type.
Definition at line 52 of file glc_interpolator.cpp.
References CalcInterpolMat(), and m_InterpolType.
void GLC_Interpolator::SetVecteurs (const GLC_Vector3d & VectDepart, const GLC_Vector3d & VectArrive)
Set start and end vector.
Definition at line 73 of file glc_interpolator.cpp.
References CalcInterpolMat(), m_EndPoint, and m_StartPoint.
Member Data Documentation
GLC_Point3d GLC_Interpolator::m_EndPoint private
End Point.
Definition at line 100 of file glc_interpolator.h.
Referenced by CalcInterpolAngulaireMat(), CalcInterpolLineaireMat(), CalcInterpolMat(), SetInterpolMat(), and SetVecteurs().
GLC_Matrix4x4 GLC_Interpolator::m_InterpolMat private
Interpolation matrix.
Definition at line 109 of file glc_interpolator.h.
Referenced by CalcInterpolAngulaireMat(), and CalcInterpolLineaireMat().
INTERPOL_TYPE GLC_Interpolator::m_InterpolType private
Interpolation type.
Definition at line 103 of file glc_interpolator.h.
Referenced by CalcInterpolMat(), SetInterpolMat(), and SetType().
GLC_Point3d GLC_Interpolator::m_StartPoint private
Start Point.
Definition at line 97 of file glc_interpolator.h.
Referenced by CalcInterpolAngulaireMat(), CalcInterpolLineaireMat(), CalcInterpolMat(), SetInterpolMat(), and SetVecteurs().
int GLC_Interpolator::m_StepCount private
Interpolation step count.
Definition at line 106 of file glc_interpolator.h.
Referenced by CalcInterpolAngulaireMat(), CalcInterpolLineaireMat(), SetInterpolMat(), and SetNbrPas().
The documentation for this class was generated from the following files:
glc_interpolator.h
glc_interpolator.cpp
©2005-2013 Laurent Ribon