GLC_lib: GLC_FileLoader Class Reference
GLC_FileLoader Class Reference
GLC_FileLoader : Create a GLC_World from file.
#include <glc_fileloader.h>
Signals
void currentQuantum (int)
Public Member Functions
Constructor / Destructor
GLC_FileLoader ()
virtual ~GLC_FileLoader ()
Set Functions
GLC_World createWorldFromFile (QFile &file, QStringList *pAttachedFileName=NULL)
Create a GLC_World from a file.
Detailed Description
GLC_FileLoader : Create a GLC_World from file.
GLC_FileLoader loads a 3D model from a file. A suitable parser is selected based on the file name extension.
Definition at line 50 of file glc_fileloader.h.
Constructor & Destructor Documentation
GLC_FileLoader::GLC_FileLoader ()
Definition at line 45 of file glc_fileloader.cpp.
GLC_FileLoader::~GLC_FileLoader () virtual
Definition at line 49 of file glc_fileloader.cpp.
Member Function Documentation
GLC_World GLC_FileLoader::createWorldFromFile (QFile & file, QStringList * pAttachedFileName = NULL)
Create a GLC_World from a file.
Definition at line 58 of file glc_fileloader.cpp.
References GLC_Factory::canBeLoaded(), GLC_3dsToWorld::CreateWorldFrom3ds(), GLC_3dxmlToWorld::createWorldFrom3dxml(), GLC_BSRepToWorld::CreateWorldFromBSRep(), GLC_ColladaToWorld::CreateWorldFromCollada(), GLC_ObjToWorld::CreateWorldFromObj(), GLC_OffToWorld::CreateWorldFromOff(), GLC_StlToWorld::CreateWorldFromStl(), currentQuantum(), GLC_FileFormatException::FileNotSupported, GLC_WorldReaderHandler::listOfAttachedFileName(), GLC_3dsToWorld::listOfAttachedFileName(), GLC_3dxmlToWorld::listOfAttachedFileName(), GLC_ObjToWorld::listOfAttachedFileName(), GLC_ColladaToWorld::listOfAttachedFileName(), GLC_Factory::loadingHandler(), and GLC_WorldReaderHandler::read().
Referenced by GLC_Factory::createWorldFromFile().
void GLC_FileLoader::currentQuantum (int) signal
Referenced by createWorldFromFile().
The documentation for this class was generated from the following files:
glc_fileloader.h
glc_fileloader.cpp
©2005-2013 Laurent Ribon