GLC_lib: GLC_Line3d Class Reference
GLC_Line3d Class Reference
GLC_Line3d : Math 3d line representation.
#include <glc_line3d.h>
Public Member Functions
Constructor / Destructor
GLC_Line3d ()
Default constructor.
GLC_Line3d (const GLC_Point3d &point, const GLC_Vector3d &vector)
Construct a 3d line with the given 3d point and vector.
GLC_Line3d (const GLC_Line3d &line)
Construct a 3d line with the given 3d line.
~GLC_Line3d ()
Destructor.
Get Functions
GLC_Point3d startingPoint () const
Return the starting 3d point of this line.
GLC_Vector3d direction () const
Return the direction vector of this line.
Set Functions
void setStartingPoint (const GLC_Point3d &point)
Set the starting point of this 3d line.
void setDirection (const GLC_Vector3d &direction)
Set the direction vector of this line.
Private Attributes
GLC_Point3d m_Point
Starting point of the 3d line.
GLC_Vector3d m_Vector
Vector of the line.
Detailed Description
GLC_Line3d : Math 3d line representation.
GLC_Line3d is definined by a 3d point and a vector
Definition at line 37 of file glc_line3d.h.
Constructor & Destructor Documentation
GLC_Line3d::GLC_Line3d ()
Default constructor.
Definition at line 26 of file glc_line3d.cpp.
GLC_Line3d::GLC_Line3d (const GLC_Point3d & point, const GLC_Vector3d & vector)
Construct a 3d line with the given 3d point and vector.
Definition at line 33 of file glc_line3d.cpp.
GLC_Line3d::GLC_Line3d (const GLC_Line3d & line)
Construct a 3d line with the given 3d line.
Definition at line 41 of file glc_line3d.cpp.
GLC_Line3d::~GLC_Line3d ()
Destructor.
Definition at line 49 of file glc_line3d.cpp.
Member Function Documentation
GLC_Vector3d GLC_Line3d::direction () const inline
Return the direction vector of this line.
Definition at line 67 of file glc_line3d.h.
Referenced by GLC_RotationManipulator::doManipulate(), glc::lineIntersectPlane(), glc::pointLineDistance(), and glc::project().
void GLC_Line3d::setDirection (const GLC_Vector3d & direction) inline
Set the direction vector of this line.
Definition at line 82 of file glc_line3d.h.
void GLC_Line3d::setStartingPoint (const GLC_Point3d & point) inline
Set the starting point of this 3d line.
Definition at line 78 of file glc_line3d.h.
GLC_Point3d GLC_Line3d::startingPoint () const inline
Return the starting 3d point of this line.
Definition at line 63 of file glc_line3d.h.
Referenced by GLC_RotationManipulator::doManipulate(), glc::lineIntersectPlane(), glc::pointLineDistance(), and glc::project().
Member Data Documentation
GLC_Point3d GLC_Line3d::m_Point private
Starting point of the 3d line.
Definition at line 91 of file glc_line3d.h.
GLC_Vector3d GLC_Line3d::m_Vector private
Vector of the line.
Definition at line 94 of file glc_line3d.h.
The documentation for this class was generated from the following files:
glc_line3d.h
glc_line3d.cpp
©2005-2013 Laurent Ribon