GLC_lib: glc_material.h File Reference
glc_material.h File Reference
interface for the GLC_Material class.
#include "../glc_object.h"
#include "glc_texture.h"
#include <QHash>
#include <QColor>
#include <QSet>
#include "../glc_config.h"
Classes
class GLC_Material
GLC_Material : OpenGL surface material properties.
Typedefs
typedef QHash< GLC_uint,
GLC_Geometry * > WhereUsed
Functions
QDataStream & operator<< (QDataStream &, const GLC_Material &)
Non-member stream operator.
QDataStream & operator>> (QDataStream &, GLC_Material &)
Detailed Description
interface for the GLC_Material class.
Definition in file glc_material.h.
Typedef Documentation
typedef QHash< GLC_uint, GLC_Geometry*> WhereUsed
Definition at line 37 of file glc_material.h.
Function Documentation
QDataStream& operator<< (QDataStream & , const GLC_Material &)
Non-member stream operator.
Definition at line 643 of file glc_material.cpp.
References GLC_Material::ambientColor(), GLC_Material::diffuseColor(), GLC_Material::emissiveColor(), GLC_Material::hasTexture(), GLC_Object::id(), GLC_Material::m_ChunkId, GLC_Object::name(), GLC_Material::opacity(), GLC_Material::shininess(), GLC_Material::specularColor(), and GLC_Material::textureHandle().
QDataStream& operator>> (QDataStream & , GLC_Material &)
Definition at line 666 of file glc_material.cpp.
References GLC_Material::m_ChunkId, GLC_Material::setAmbientColor(), GLC_Material::setDiffuseColor(), GLC_Material::setEmissiveColor(), GLC_Object::setId(), GLC_Object::setName(), GLC_Material::setOpacity(), GLC_Material::setShininess(), GLC_Material::setSpecularColor(), and GLC_Material::setTexture().
©2005-2013 Laurent Ribon