GLC_lib: glc_3drep.cpp File Reference
glc_3drep.cpp File Reference
#include "glc_3drep.h"
#include "../glc_factory.h"
#include "glc_mesh.h"
#include "glc_errorlog.h"
Functions
QDataStream & operator<< (QDataStream &stream, const GLC_3DRep &rep)
Non-member stream operator.
QDataStream & operator>> (QDataStream &stream, GLC_3DRep &rep)
Function Documentation
QDataStream& operator<< (QDataStream & stream, const GLC_3DRep & rep)
Non-member stream operator.
Definition at line 430 of file glc_3drep.cpp.
References GLC_3DRep::m_ChunkId, GLC_3DRep::m_pGeomList, GLC_3DRep::materialSet(), GLC_Rep::name(), and GLC_Mesh::saveToDataStream().
QDataStream& operator>> (QDataStream & stream, GLC_3DRep & rep)
Definition at line 465 of file glc_3drep.cpp.
References GLC_3DRep::addGeom(), glc::GLC_GenID(), GLC_Object::id(), GLC_3DRep::isEmpty(), GLC_Mesh::loadFromDataStream(), GLC_3DRep::m_ChunkId, GLC_Object::setId(), and GLC_Rep::setName().
©2005-2013 Laurent Ribon