GLC_lib: glc_project.cpp File Reference
glc_project.cpp File Reference
#include "../glc_context.h"
#include "glc_glu.h"
Macros
#define __glPi 3.14159265358979323846
Functions
static void __gluMakeIdentityd (GLdouble m[16])
static void __gluMakeIdentityf (GLfloat m[16])
static void normalize (float v[3])
static void cross (float v1[3], float v2[3], float result[3])
static void __gluMultMatrixVecd (const GLdouble matrix[16], const GLdouble in[4], GLdouble out[4])
static int __gluInvertMatrixd (const GLdouble m[16], GLdouble invOut[16])
static void __gluMultMatricesd (const GLdouble a[16], const GLdouble b[16], GLdouble r[16])
Macro Definition Documentation
#define __glPi 3.14159265358979323846
Definition at line 83 of file glc_project.cpp.
Referenced by glc::gluPerspective().
Function Documentation
static int __gluInvertMatrixd (const GLdouble m[16], GLdouble invOut[16]) static
Definition at line 188 of file glc_project.cpp.
static void __gluMakeIdentityd (GLdouble m[16]) static
Definition at line 62 of file glc_project.cpp.
Referenced by glc::gluPerspective().
static void __gluMakeIdentityf (GLfloat m[16]) static
Definition at line 70 of file glc_project.cpp.
Referenced by glc::gluLookAt().
static void __gluMultMatricesd (const GLdouble a[16], const GLdouble b[16], GLdouble r[16]) static
Definition at line 238 of file glc_project.cpp.
static void __gluMultMatrixVecd (const GLdouble matrix[16], const GLdouble in[4], GLdouble out[4]) static
Definition at line 170 of file glc_project.cpp.
static void cross (float v1[3], float v2[3], float result[3]) static
Definition at line 120 of file glc_project.cpp.
Referenced by glc::gluLookAt().
static void normalize (float v[3]) static
Definition at line 108 of file glc_project.cpp.
Referenced by GLC_ExtrudedMesh::computeGivenFaceNormal(), GLC_CuttingPlane::create3DviewInstance(), GLC_Camera::createMatComp(), GLC_Arrow::createWire(), GLC_RotationManipulator::doManipulate(), GLC_FlyMover::fly(), glc::gluLookAt(), GLC_CuttingPlane::moveManipulatorRep(), GLC_Matrix4x4::setMatRot(), and GLC_Camera::sideVector().
©2005-2013 Laurent Ribon