GLC_lib: glc_colladatoworld.h File Reference
glc_colladatoworld.h File Reference
interface for the GLC_ColladaToWorld class.
#include <QObject>
#include <QString>
#include <QFile>
#include <QXmlStreamReader>
#include <QHash>
#include <QColor>
#include "../shading/glc_material.h"
#include "../geometry/glc_mesh.h"
#include "../sceneGraph/glc_structoccurence.h"
#include "../glc_config.h"
Classes
class GLC_ColladaToWorld
GLC_ColladaToWorld : Create an GLC_World from dae file.
struct GLC_ColladaToWorld::InputData
struct GLC_ColladaToWorld::ColladaVertice
struct GLC_ColladaToWorld::MatOffsetSize
struct GLC_ColladaToWorld::Accessor
struct GLC_ColladaToWorld::MeshInfo
struct GLC_ColladaToWorld::ColladaNode
Functions
bool operator== (const GLC_ColladaToWorld::ColladaVertice &vertice1, const GLC_ColladaToWorld::ColladaVertice &vertice2)
uint qHash (const GLC_ColladaToWorld::ColladaVertice &vertice)
Detailed Description
interface for the GLC_ColladaToWorld class.
Definition in file glc_colladatoworld.h.
Function Documentation
bool operator== (const GLC_ColladaToWorld::ColladaVertice & vertice1, const GLC_ColladaToWorld::ColladaVertice & vertice2) inline
Definition at line 449 of file glc_colladatoworld.h.
References GLC_ColladaToWorld::ColladaVertice::m_Values.
Referenced by GLC_Plane::operator!=(), and GLC_Matrix4x4::operator!=().
uint qHash (const GLC_ColladaToWorld::ColladaVertice & vertice) inline
Definition at line 452 of file glc_colladatoworld.h.
References GLC_ColladaToWorld::ColladaVertice::m_Values.
Referenced by GLC_Material::hashCode(), and qHash().
©2005-2013 Laurent Ribon