GLC_lib: glc_geomtools.cpp File Reference
glc_geomtools.cpp File Reference
implementation of geometry function.
#include "glc_geomtools.h"
#include "glc_matrix4x4.h"
#include <QtGlobal>
Functions
GLC_Vector2d round (const GLC_Vector2d &vector)
GLC_Vector2d round (const GLC_Vector2d &vector, double accuracy)
GLC_Vector3d round (const GLC_Vector3d &vector)
GLC_Vector3d round (const GLC_Vector3d &vector, double accuracy)
Detailed Description
implementation of geometry function.
Definition in file glc_geomtools.cpp.
Function Documentation
GLC_Vector2d round (const GLC_Vector2d & vector)
Definition at line 642 of file glc_geomtools.cpp.
References glc::round(), GLC_Vector2d::x(), and GLC_Vector2d::y().
GLC_Vector2d round (const GLC_Vector2d & vector, double accuracy)
Definition at line 649 of file glc_geomtools.cpp.
References glc::round(), GLC_Vector2d::x(), and GLC_Vector2d::y().
GLC_Vector3d round (const GLC_Vector3d & vector)
Definition at line 656 of file glc_geomtools.cpp.
References glc::round(), GLC_Vector3d::x(), GLC_Vector3d::y(), and GLC_Vector3d::z().
GLC_Vector3d round (const GLC_Vector3d & vector, double accuracy)
Definition at line 663 of file glc_geomtools.cpp.
References glc::round(), GLC_Vector3d::x(), GLC_Vector3d::y(), and GLC_Vector3d::z().
©2005-2013 Laurent Ribon