GLC_lib: glcXmlUtil Namespace Reference
glcXmlUtil Namespace Reference
Functions
bool goToElement (QXmlStreamReader *pReader, const QString &element)
Go to the given xml Element, return true on succes.
QString getContent (QXmlStreamReader *pReader, const QString &element)
QString readAttribute (QXmlStreamReader *pReader, const QString &attribute)
Read the specified attribute.
bool endElementNotReached (QXmlStreamReader *pReader, const QString &element)
Return true if the end of specified element is not reached.
bool startElementNotReached (QXmlStreamReader *pReader, const QString &element)
Return true if the start of specified element is not reached.
void goToEndElement (QXmlStreamReader *pReader, const QString &element)
Go to the end Element of a xml.
Function Documentation
bool glcXmlUtil::endElementNotReached (QXmlStreamReader * pReader, const QString & element) inline
Return true if the end of specified element is not reached.
Definition at line 84 of file glc_xmlutil.h.
Referenced by GLC_ColladaToWorld::CreateWorldFromCollada(), getContent(), GLC_ColladaToWorld::getContent(), goToEndElement(), GLC_ColladaToWorld::goToEndElement(), GLC_ColladaToWorld::loadAccessor(), GLC_ColladaToWorld::loadCommonColorOrTexture(), GLC_ColladaToWorld::loadController(), GLC_ColladaToWorld::loadEffect(), GLC_ColladaToWorld::loadGeometry(), GLC_ColladaToWorld::loadImage(), GLC_ColladaToWorld::loadInstanceController(), GLC_ColladaToWorld::loadInstanceGeometry(), GLC_ColladaToWorld::loadLibraryContollers(), GLC_ColladaToWorld::loadLibraryEffects(), GLC_ColladaToWorld::loadLibraryGeometries(), GLC_ColladaToWorld::loadLibraryImage(), GLC_ColladaToWorld::loadLibraryMaterials(), GLC_ColladaToWorld::loadLibraryNodes(), GLC_ColladaToWorld::loadMaterial(), GLC_ColladaToWorld::loadMaterialTechnique(), GLC_ColladaToWorld::loadMesh(), GLC_ColladaToWorld::loadNewParam(), GLC_ColladaToWorld::loadNode(), GLC_ColladaToWorld::loadPolygons(), GLC_ColladaToWorld::loadPolylist(), GLC_ColladaToWorld::loadProfileCommon(), GLC_ColladaToWorld::loadSampler2D(), GLC_ColladaToWorld::loadScene(), GLC_ColladaToWorld::loadShininess(), GLC_ColladaToWorld::loadSurface(), GLC_ColladaToWorld::loadTechnique(), GLC_ColladaToWorld::loadTechniqueCommon(), GLC_ColladaToWorld::loadTransparency(), GLC_ColladaToWorld::loadTriangles(), GLC_ColladaToWorld::loadVertexBulkData(), and GLC_ColladaToWorld::loadVisualScenes().
QString glcXmlUtil::getContent (QXmlStreamReader * pReader, const QString & element) inline
Definition at line 64 of file glc_xmlutil.h.
References endElementNotReached().
bool glcXmlUtil::goToElement (QXmlStreamReader * pReader, const QString & element) inline
Go to the given xml Element, return true on succes.
Definition at line 55 of file glc_xmlutil.h.
void glcXmlUtil::goToEndElement (QXmlStreamReader * pReader, const QString & element) inline
Go to the end Element of a xml.
Definition at line 94 of file glc_xmlutil.h.
References endElementNotReached().
QString glcXmlUtil::readAttribute (QXmlStreamReader * pReader, const QString & attribute) inline
Read the specified attribute.
Definition at line 79 of file glc_xmlutil.h.
bool glcXmlUtil::startElementNotReached (QXmlStreamReader * pReader, const QString & element) inline
Return true if the start of specified element is not reached.
Definition at line 89 of file glc_xmlutil.h.
Referenced by GLC_ColladaToWorld::goToElement().
©2005-2013 Laurent Ribon